### ISSUE TITLE
[Spell/Warrior] Charge (ignoring moving path)

### ISSUE THREAD

**Issue by Xman993** [WoWManiaUK/Blackwing-Lair#1273]
**Links:**

![ezgif com-optimize](https://user-images.githubusercontent.com/6819293/55321830-eb2f4e00-547a-11e9-8eae-418089fb5947.gif)

I record it to see what happens. 

**What is happening:**

This is what i call a assasin Charge. I use the charg mid air. and hit the target like nothing heppens. 

**What should happen:**

Charge need to follow the path. and u cant use it in mid air. u need to have ground under you'r feet's

**Comment by bagi84** [comment]
Charge has always been able to be use mid air (jump or after being knock up) on both warriors and Feral charge on druids (commonly refered to as a bear bomb on retail with druids. Flight form toward target mid air shift out of flight form into bear and charge for fast engage and no fall damage.). as for after the charge has stopped if ur still in mid air like it ssem you are that could be due to the environmental textures or a slight visual bug.
