### ISSUE TITLE
[Object] Arena treasure chest

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#135]
Gurubashi arena treasure chest is not located in arena, I am only person on server playing, so technically chest should be there, but it aint.
https://www.wowhead.com/object=179697/arena-treasure-chest

this is not leveling matter, but it is pretty ``important`` thing, barging rights, achievement, and nice low level trinket.

**Comment by wow-mania** [comment]
The chest is placed once every 3h and despawns in 5min. So you need to be there when it does.

**Comment by TheSale** [comment]
oh I thought it will sit there for hours or till looted, I will check in 30 min I guess 21h server time then 00:00?

**Comment by TheSale** [comment]
I finally got chest 3am local time, 2am server time
very nice

**Comment by Echinaceax** [comment]
### Update 


note: due to daylight saving 

![image](https://user-images.githubusercontent.com/39439201/112739673-76fae880-8f76-11eb-9ca8-9dae7f545972.png)


https://wowwiki-archive.fandom.com/wiki/Gurubashi_Arena

- [ ] Timers are off on this atm they are doing 11pm - 2am etc...
- [ ] Despawn timer is off slightly


**what should happen** 
- timers should be 12 - 3 - 6 - 9 - etc...
- despawn after 5 mins if not collected 

![image](https://user-images.githubusercontent.com/39439201/112739608-f805b000-8f75-11eb-8a28-0fc1a3be0c1d.png)
