### ISSUE TITLE
[Spell/pala] Light of Dawn - 85222

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1399]
**Links:**

https://cata-twinhead.twinstar.cz/?spell=85222

**What is happening:**
- [ ] Light of Dawn Not Scaling with the amount of Holy Power Charges available but removing all charges when used.

**What should happen:**
Abilities used for Examples above Should behave, scale and modify spell effects  as described in their links above.

main tester @bagi84

**Comment by Keader** [comment]
why closed?

**Comment by Echinaceax** [comment]
> why closed?

because bagi explained that its the holy power that is the issue #1396

**Comment by Keader** [comment]
fixed.

**Comment by Dranah** [comment]
Well it scales with holy power somewhat now, but the spell generally overscales as hell. Both the base healing looks multiplied and the SP coefficient is somehow off.

**Numerically:**
TEST1:Naked pallie with like 160 sp, base healing being around average 650 it calculates intended heal ~727 with 1 HP, twice of that (1,4k) with 2 and thrice (2,1k) with 3.
What it actually heals is ~3k with 1 HP, 4,5k with 2, and ~6k with 3.
TEST2: with 2k spell power, the calculated healing is 997, actual healing 3,6k for 1 HP, 5,1k or 2 HP, and 7k for 3.

This tells me that roughly
1) the spell heals for 4x the intended by default and each holy power adds double the intended as extra
2) the sp coefficient is added twice (approx 30% instead of 15%) to the 1-holy power version, however does not scale properly with the multiplication afterwards. 

**How it should work:** Intended values
BasePoints = 605,77 to 674,92
Spell coefficient 13,2% per holy power.
The healing with 2 hp must be exactly double of 1 HP and the healing with 3 HP must be exactly triple.
