### ISSUE TITLE
[Issues] Flight points opening with levels- Alliance

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#1529]
**Links:**
none available
from WoWHead or our Armory

**What is happening:**
As I'm levelling I'm unlocking more flight points across the map in locations I've never been. not sure this is a bug or not cant find any reference to it on Wowhead regarding this.

**Comment by sarahkay88** [comment]
yup same here

**Comment by Echinaceax** [comment]
@bagi84 - i do know with what another tester told me, and thats that as you lvl (hero's call board) opes that next zone with FP for you

**Comment by bagi84** [comment]
that's why I raised the issue I can find references for it unlocking new questing areas but nothing about it granting new flight paths

**Comment by Echinaceax** [comment]
yes i was really surprised too when Rep told me, ive always ran to the next zone to get the FP lol

**Comment by Dranah** [comment]
here's the correspondant article from wowpedia:
Then, in Patch 4.0.3a, flight paths changed for the release of Cataclysm to reflect the revised world. Many zones received additional flight paths that make traveling within the zone faster and easier. And in some zones, flight paths disappeared or appeared due to changes in Alliance and Horde control. To remedy the breaking of some flight paths, characters now received all undiscovered flight points zone-by-zone on reaching suitable character levels. This had the effect of immediately granting many players knowledge of flight paths they had not known before Patch 4.0.3a. Characters were also automatically given all flight points for many faction-specific low-level zones upon creation.

In Patch 5.2.0 the Cataclysm changes were reverted, with flight points no longer automatically discovered.

This is an intended feature specifically for cataclysm. Before and after cataclysm, it worked the way you describe (need to talk to a flight master to unlock path)
