### ISSUE TITLE
[NPC/SPELL] Baron Silverlaine - id 3887 -Shadowfang keep

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#1605]
**Links:**
NPC -https://www.wowhead.com/npc=3887/baron-silverlaine
SPELL -https://www.wowhead.com/spell=93857/summon-worgen-spirit
from WoWHead or our Armory

**What is happening:**

when NPC/BOSS is using the ability the spirit appears forming one of the worgen spirirts but instead of it using the abilities describe for that spirit form they are just exploding and wiping the party.
This spell has a random chance of calling on of the Pre cata worgen bosses back as a simple to kill add for this boss.
Summonable Worgens:
 Rethilgore
 Razorclaw the Butcher
 Odo the Blindwatcher
 Wolf Master Nandos with three Lupine Spectres

**What should happen:**

The spirits summoned should use the abilities described in the tooltip in ingame  dungeon guide not exploding and causing mass damage

**Comment by Dranah** [comment]
I've seen this with Rethilgore, it is not an explosion, but he had an aura that deals 2000 damage per second to all party members (which instakills the level 20 guys).
Probably a wrong spell ID that was added, because none of the adds are supposed to have any damaging auras.

Here are the spells that **should** be cast by the adds, anything else shouldn't be present in their scripts:
https://www.wowhead.com/npc=50857/odo-the-blindwatcher >https://www.wowhead.com/spell=93952/blinding-shadows and https://www.wowhead.com/spell=93931/howling-rage
https://www.wowhead.com/npc=50869/razorclaw-the-butcher >  https://www.wowhead.com/spell=93930/spectral-ravaging https://www.wowhead.com/spell=93914/spectral-rush
https://www.wowhead.com/npc=50834/rethilgore > https://www.wowhead.com/spell=93863/soul-drain

I've found no issues with Wolf Master Nandos.

**Comment by Keader** [comment]
Fixed.
