### ISSUE TITLE
[Group] Lag issue 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1616]
**Links:**

**What is happening:**
Yesterday we grouped (5 testers) to do a dungeon (test guild rep etc...)
Outside of the dungeon we experienced really bad lag, for me i was in Stormwind, 
other grouped testers will add their locations themselves. lag dissipated when we all left the group.

our group did 4 dungeon runs i think, and group lag after leaving the dungeon was insane.

**Location** for me was outside stockades / Stormwind

note: Another Tester also had group lag in Barrens (not our group) 
so two unrelated separate groups experienced lag 

**What should happen:**
- Shouldn't be laggy, they all have high end PCs :)

**Comment by Dranah** [comment]
Just to be clear, is this delay (ms lag) or framerate issue (fps lag)?

**Comment by Echinaceax** [comment]
@Dranah - nope, 
we test team had normal fps and ms ..this is why it was wierd tbh ...
then i remembered the other new tester has also previosly said they had lag in a grpoup in Barrens 
(i did ask them to report it) but didnt ..so it was forgoten about until we had same issue (and we was all in different zones (which was the wierd thing) so i reported

**Comment by Dranah** [comment]
Interesting. I have experienced this group lag the other day, but I cannot seem to repro it on PTR.
Things ive tried
- Distance
- FLight path
- Quests in log
- Player auras: ferocious inspiration, devotion aura etc...

**Comment by wow-mania** [comment]
lag is not a server side issue.

**Comment by Echinaceax** [comment]
> lag is not a server side issue.

@wow-mania 
interesting ...what can it be then?

**Comment by Frostmanx** [comment]
@wow-mania it's still happening ,its not a latency lag but a FPS drop when in a group of more than 3 people and when there are all in different zones and the closer we get to each other the FPS improves a little bit and if we enter a dungeon its back to 60 fps. Also soon as we leave group its back to normal fps.

p.s - I have a high end computer :)

**Comment by Dranah** [comment]
It could be a client issue, since I have never experienced anything similar on a regular cata client, only on wow-reign's. But in this case, it needs to be fixed from reign's client side (like visual issues).
The lag in this case is an extreme FPS drop when , as frostmanx says, more than 3 people are in group and they are scattered in different zones. It affects every person in the group, all of them being on the correct fresh 1.0.4 client.
I have to emphasize, as soon as people would attempt raiding, this would be a GIANT issue.
You cannot organize a pug raid (where 10 or 25 players are invited over 30-40minutes each being scattered in the world) if it incapacitates each raid member from performing any task due to having zero FPS.

**Comment by Frostmanx** [comment]
Yes this might turn out to be a population killer if it's not fixed soon enough. Since most players are reaching 85 and looking to start doing dungeons and when they experience this it can be quite frustrating. Also I think this should be Main priority and should be fixed asap!

**Comment by wow-mania** [comment]
nothing on the server-side
may be a network or something else but nothing I can do without more info

Server diff is never above 50ms

**Comment by Dranah** [comment]
This is being looked at. May take some time to fix but please leave report open for reference.

**Comment by Frostmanx** [comment]
Video for reference  
https://streamable.com/llooe

**Comment by Echinaceax** [comment]
New info for @wow-mania 
More screen freeze when on FP but is still screen freezing no matter if flighing or not

**Comment by Keader** [comment]
Sending a fix now.

**Comment by Keader** [comment]
I'm pretty sure that it will work.
I need say many thanks to Elon/Ovahlord for all help in this issue.

**Comment by Sammy974** [comment]
Please re-open this report because the issue is not fixed. Lot of people is experiencing an hard FPS drop when in party and distant from each other atm. Some more, some less, but it's still a bad issue and need to be fixed. A guild mate of mine can't leterally move if we're in a dungeon and someone of us teleport out for some reason. I'm having this issue too, but i still can move although with great difficulty. It would be great to make some test and discover the cause of that, either if it's a server o client issue.

**Comment by Keader** [comment]
I need a reproduce case for it.

**Comment by Echinaceax** [comment]
@Sammy974 Cant you take a team in dev and try and reproduce for Keader ?
we still need this fixing

**Comment by Sammy974** [comment]
@Echinaceax  sure, but he has to be with us to see what's happening i guess

**Comment by Jimpaa** [comment]
Massiv fps loss when we made a 25man grp all over the world. The first pack in BoT gave me some issues aswell and we got to the first boss it was all fine.

**Comment by Echinaceax** [comment]
Players still having issues with this
Im going to reset this because since i fixed my addon issue i havent really retested this for others

**Comment by Echinaceax** [comment]
this is what we mean by different phase @Rushor  @wow-mania  @Keader 

![diff phase](https://user-images.githubusercontent.com/39439201/77247224-3ebc1e00-6c2f-11ea-910c-083457e4a1fd.jpg)

please can someone figure this out, it is annoying that we cant group as the game intended.

Raiders/players have to make there own way to raids/World bosses to stop this happening and inv to group when they all get there. 

God knows what BGs are going to be like, havent got to test these with group yet :(

**Comment by Echinaceax** [comment]
Fixed here #4192
closing this one
