### ISSUE TITLE
[Dungeon] Vote Kick Not Working

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1617]
**What is happening:**
Vote Kick is not working even tho everyone voted yes. After all vote kick has been tried on every single group member, it says "Another votekick is already in progress"

**What should happen:**
You should be able to votekick other people if the vote is positive.

**Comment by giles1508** [comment]
ok this needs fixing ASAP,   if someone rage quits,   the rest of the group cannot remove the player,  so the dungeon is over,  and they are saved to it because  this  ticket  ---    https://github.com/WoWManiaUK/Blackwing-Lair/issues/2393
saves you to every heroic when you queue for random,   these 2 tickets really need to be fixed now,   we are starting to increase player base,   ive noticed players joining from other servers,   and this is really becoming an issue !

**Comment by Denrunmt** [comment]
We got an afk player too, so we can't replace him because of the kick voting not working. Please investigate fixing it as soon as possible. A lot of people get saved because they can't replace the rage quiters/afkers or people that got dc and never came online. 

![InkedScreenshot_1_LI](https://user-images.githubusercontent.com/52254524/60536070-32dda400-9d0e-11e9-9081-f31e24db4e50.jpg)
![InkedScreenshot_2_LI](https://user-images.githubusercontent.com/52254524/60536093-3e30cf80-9d0e-11e9-900a-4984cd8f2ca3.jpg)
![InkedScreenshot_3_LI](https://user-images.githubusercontent.com/52254524/60536100-41c45680-9d0e-11e9-9e24-a64aac00ad3f.jpg)

**Comment by Echinaceax** [comment]
@Keader can we get this fixed asap please (important reasons)

**Comment by Keader** [comment]
Asap? Impossible.
Last weeks of my semester, doing alot of uni stuffs.

**Comment by Keader** [comment]
Fixed.
Sorry for delay, now i'm free again o.o
