### ISSUE TITLE
[Item/Weapon] Haunting Blade

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1627]
**Links:**
ITEM - https://www.wowhead.com/item=6641/haunting-blade

**What is happening:**
This sword is hitting for way too much compared to what it should (230 per hit at lvl 20 with such a weapon is oneshotting basically)

**What should happen:**
Should decrease the damage of this weapon

**Comment by Kitzunu** [comment]
https://cata-twinhead.twinstar.cz/?item=6641

**Comment by Dranah** [comment]
Cannot reproduce any issue here.
Equipping the sword alone properly adds its dps to your white melee. At this point you are doing approx 50-60 damage on an armored dummy with it.
Speccing into ret properly increases this melee damage by 25%, any items and buffs on you further boost it to the point your melee white hits for 100-120 damage. (i tested just with 4 looms, possibly you can pump it up to 150 with twink gear)
Now, this damage is completely normal.
An average level 20 player or mob has ~500-600 health. Most classes on cataclysm are able to take this out in 3-4 hits at level 20 (some casters even in two), assuming they are in heirloom/good blue quality gear like the weapon above.

This weapon is extremely good due to its higher damage and slower speed, probably best at the level range. But it's not overpowered and not broken.
