### ISSUE TITLE
[Class] Priest's Spell Mana Cost vs Usage

### ISSUE THREAD

**Issue by DiomacheTharghan** [WoWManiaUK/Blackwing-Lair#1645]
**Links:**
NONE

**What is happening:**
Started to level a priest, tooltip says my Smite should cost 12 mana. In fact tho, it cost 20 mana, and it's escalating and the problem is making people that play priest struggling on mana management.

![WoWScrnShot_042519_192704](https://user-images.githubusercontent.com/44828921/56755699-66410700-6790-11e9-8101-8002bbf1a1bb.jpg)

![WoWScrnShot_042519_192929](https://user-images.githubusercontent.com/44828921/56755741-7d7ff480-6790-11e9-9b32-d508587933a0.jpg)

**What should happen:**
Should cost less compared to what it is, aka should just do what the tip says.

**Comment by sarahkay88** [comment]
https://www.wowhead.com/spell=71841/smite

**Comment by Dranah** [comment]
@sarahkay88 wrong ID link, Priests' smite is https://www.wowhead.com/spell=585
Of course its updated to BFA on wowhead, so you should see in the changelog "before build 4.1something)
The spell cost is 15% of base mana.

**Maths:**
How much is the base mana for a level 1 priest?
Take your shown mana value and deduct the amount given by Int.
**TEST1**: I have 220 mana on my blood elf priest lvl 1, My 26 intellect provides 110 of that. So my base mana is 110.
15% of 110 mana is 16~
My tooltip says smite costs 10 mana, but it indeed costs 16. The tooltip is wrong, the mana cost is correct. Unfair (compared to other casters), but blizzlike.

**TEST2**: Now, your priest is a level 3 troll. I re-created that, since each race has slightly different base stats and values.
Level 3 troll priest = 164 total mana, 35 of that given by Int. Base mana is then 129.
15% of 129 is ~19.
Tooltip says it costs 12 mana but it really costs 19. Again, tooltip is wrong, mana cost is correct. Unfair, but correct.

Yes, leveling a priest on cata sucks (not like on wotlk it didnt, but on cata other classes became butter easy in comparison). Disc is generally the way to go because they get 50% combat regen innately at lvl 10, until then you just gotta survive somehow. 
Here is a blizz forum topic debating over how inbalanced it is: https://eu.battle.net/forums/en/wow/topic/1849929966
NOTE: priest mana management at higher levels (70+) becomes normalized. Blizz only fucked the scaling for lower ranges...
