### ISSUE TITLE
[Spell] Primal Madness

### ISSUE THREAD

**Issue by Melagis** [WoWManiaUK/Blackwing-Lair#1710]
**Links:**

https://cata-twinhead.twinstar.cz/?spell=80316

**What is happening:**
Doesn't increase maximum energy or current.

**What should happen:**
Tiger's Fury and Berserk also increase your current and maximum Energy by 10 during their durations, and your Enrage and Berserk abilities instantly generate 6 Rage.

**Comment by Keader** [comment]
Wrong ticket name.
Is Primal Madness.

**Comment by Echinaceax** [comment]
> Primal Madness

https://wowwiki.fandom.com/wiki/Primal_Madness

Only referance i see atm

**Comment by Keader** [comment]
![image](https://user-images.githubusercontent.com/7120913/57635142-fa76e080-757c-11e9-965d-eaf6e9c6569f.png)

**Comment by Dranah** [comment]
**Cat form:** 
Tiger's fury properly increases both current and max energy (fixed)
Berserk (50334) increases maximum energy but does not increase current. (need fix)
**Bear form:**
Enrage (5229) generates a total of 44 rage instantly, instead of the intended 32 after taking the talent (need fix)
Berserk (50334) does not generate the instant 12 rage it should (need fix)
