### ISSUE TITLE
[Spell] Pulverize.

### ISSUE THREAD

**Issue by Melagis** [WoWManiaUK/Blackwing-Lair#1729]
**Links:**

https://cata-twinhead.twinstar.cz/?spell=80313

**What is happening:**
Does not give buff and doesnt consume Lacerate.

**What should happen:**

**Comment by Dranah** [comment]
The damage is kinda off. The base damage is way too high, the scaling with stacks is a tad too low.
**How it should work:**
Should be 60% of melee swing damage , increased by 1624 per stack of lacerate consumed.
**How it works atm:**
Test char with 1308-1309 melee damage (char sheet).
With no stacks of lacerate it should deal 60% of that, being 780~ damage on a target with no armor at all and approx 500-600 damage on a dummy.
What it deals is 2,4k base damage instead, which is well about 4-5x higher.
It does consume Lacerate stacks now, although the damage it gains per-stack is below the intended (~1200 damage per stack instead of 1624 atm).
