### ISSUE TITLE
[Spell] Mail Specialization - Shaman - 86529

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#1807]
**Links:**

spell ID 86529 >> This is the spell that hunters have in their spellbook and need to learn.

But the trainers teach wrong ID. They teach ID 87507 instead, which does not give you the ability you need.

How it should work: Hunters trainers need to teach the correct spell ID (86529)
ID 87507 must not be taught

**Comment by Keader** [comment]
but even with correct ID, they can equip all items?

**Comment by Echinaceax** [comment]
> but even with correct ID, they can equip all items?

havent checked tbh @Keader , i'll ask in channel

**Comment by kDracku** [comment]
Hello (Elemental Shaman here)
Yes your learn Mail Specialization from trainer ( but is the wrong one) cuz when you browse the spellbook it says you need to visit your trainer for Mail specialization
And yes you can equip all your mail items but you dont get bonus since the spell is not learned proprely

**Comment by Kitzunu** [comment]
This just has to be changed in npc_trainer to the correct spell

**Comment by Dranah** [comment]
@Keader it's not about equipping, it's about getting a bonus stat reward for equipping mail in EVERY slot
you're confusing it with the ability "mail armor" which enables them to use mail armor in the first place (at lvl 40)
