### ISSUE TITLE
[Quest] Fourth and Goal -24503- Kezan

### ISSUE THREAD

**Issue by Shycazia** [WoWManiaUK/Blackwing-Lair#1849]
**Links:**
https://www.wowhead.com/quest=24503/fourth-and-goal
https://www.youtube.com/watch?v=-HzURtga_FA

**What is happening:**
There is no Bilgewater Buccaneer to get in and shoot the Goal

**What should happen:**
In the Youtube Video you see what should happen 
The Bilgewater Buccaneer should stand on the field to get in and shoot the Goal through the two chimneys.

**Comment by sarahkay88** [comment]
item id https://www.wowhead.com/npc=37203

**Comment by fuzzydunlop** [comment]
Just tried this, the Bilgewater Buccaneer spawns now, and you can shoot the ball between the 2 chimneys. It actually spawns the little event of Deathwing coming in (but he's slowly walking through the air instead of flying) and he says only one line. The quest won't complete though. the .bq [questID] is not working for this quest though.
