### ISSUE TITLE
[Dungeon/NPC] Faceless Sapper - Throne of the Tides 

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#1893]
**Links:**
https://www.wowhead.com/npc=44752/faceless-sapper

**What is happening:**
those 1-2 faceless sapper glitch under the map.
![WoWScrnShot_051519_182638](https://user-images.githubusercontent.com/50077942/57794185-60ad6000-7743-11e9-9085-03a22083d00c.jpg)

**What should happen:**
they shoud standt in place so we can kill em to finish the instance.
first time we dit this ozumat few days before it was workeing perfect.

somehow it worked again i dont know how to delte things here sorry.

**Comment by Dranah** [comment]
Happens quite frequently but not every time. Need to add some protection to bring it back if they fall, it's impossible to finish the fight if they are in texture.

**Comment by Sammy974** [comment]
It just happened to my party 3 times in a row. No way to get the dungeon finished...

**Comment by Dranah** [comment]
Turns out this happens if the mob is engaged with a non-direct attack.
It can be steadily reproduced and completely avoided by making sure you don't use DoTs or debuffs as an opener (which normally, quite frequently are...)
There are no problems finishing the dungeon if you stick to that rule.
Nonetheless, needs fixing.

**Comment by Rushor** [comment]
alright savety check added. so they no longer are unter the grund. and if so, they teleport on the surface again.

![I](https://i.imgur.com/QhMQIZ9.jpg)
![I](https://i.imgur.com/KoVw7TB.jpg)
