### ISSUE TITLE
[Dungeon] BRC Raz does not kill all the bridge.

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Blackwing-Lair#1942]
**Links:**

https://www.wowhead.com/npc=39670/raz-the-crazed
**What is happening:**
Raz kills all adds but one, aggroes said add, then leaves. Causing add to evade for a while then reset.

**What should happen:**

In BRC after first boss kill, Raz should kill all the bridge adds.

**Comment by Dranah** [comment]
There are issues with his AI. Not priority atm.

**Comment by Denrunmt** [comment]
There is a new bug atm. Raz didn't get out of his cage to come and kill adds. We had to kill them by ourselves. I don't know if it happens every time but I decided to report it since it should work every time. 
![Screenshot_4](https://user-images.githubusercontent.com/52254524/61654423-13aab480-acc5-11e9-9776-194d52e637d9.png)
![Screenshot_6](https://user-images.githubusercontent.com/52254524/61654426-16a5a500-acc5-11e9-8569-ad11771f41ae.png)

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/62712831-48787480-ba04-11e9-8686-cb604a6248c0.png)

**Comment by Eirolla** [comment]
![image](https://user-images.githubusercontent.com/26048748/63156126-b2a0a300-c01c-11e9-81c4-ed2ed9fcdf7f.png)
stuck v2.0

**Comment by Rushor** [comment]
moved to https://github.com/WoWManiaUK/Blackwing-Lair/issues/3680
