### ISSUE TITLE
[Group Loot] Visual display

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2041]
**Links:**
http://i67.tinypic.com/2djq87m.jpg
**What is happening:**
As you can see in the picture he roll with greed over need that should not happen
**What should happen:**
Well you should win with need before greed (imagine happend in pug raids ^^)

**Comment by Kitzunu** [comment]
Well too be fair you cant see anything since that is not a link to a screenshot :P

**Comment by kDracku** [comment]
Done , edit :D Sorry

**Comment by Kitzunu** [comment]
Well something is way off since the other guy greeded for over 100 as well

![image](https://user-images.githubusercontent.com/24550914/58357047-ad96e200-7e79-11e9-8e30-8d2a8e18dca0.png)

**Comment by kDracku** [comment]
Still need is need , greed is greed . But yeah he rolled 128 and this happens for every greed roll

**Comment by TheSale** [comment]
happen to me as well in group person with greed rolled over 100

**Comment by sarahkay88** [comment]
Same thing happens for a DE roll they roll over 100.

**Comment by Dranah** [comment]
This is a visual bug, notice both greed rolls shown belong to "wildtusk"
The roll for 7 is his actual roll, the 128 is a random value always displayed and it has no effect on the outcome of the roll.
There is nothing about greed overriding need here, because there is no need roll on the screen shown.
The "selected need" message is a visual bug, it always shows that, without actually selecting need.
(PS: I don't think you have selected need by accident, you don't seem sure what you pressed and since the display shows need so you assumed you needed, but in fact you passed.)
The roll decides based on what you ACTUALLY pressed and only shows the result for the people who pressed need or greed. In this case this was only Wildtusk greeding, and he rolled 7. 

The visual issue needs adjusting but as it is only cosmetic, not a huge priority.

**Comment by sarahkay88** [comment]
Yea I noticed yesterday but forgot to add, I also noticed that even when you pass on loot it says you needed on it, so that's what the ss could be showing. The need may have actually been a pass which would be why the greed won.

**Comment by Kitzunu** [comment]
I think this is client issue
