### ISSUE TITLE
[Spell} Maul 

### ISSUE THREAD

**Issue by giles1508** [WoWManiaUK/Blackwing-Lair#2073]
**Links:**

https://cata-twinhead.twinstar.cz/?spell=6807   link to the spell

**What is happening:**

https://youtu.be/xDbVTzHQy3g   -  video of damage done by maul with glyph of maul
https://youtu.be/YZKWfnRKVHI   -  video of damage done by maul without glyph of maul equipped

maul is giving incorrect damage,   far too low,  doesnt look like it has scaled with level or attack power,  as another 85 druid tested with me and was doing the same dmg with far less gear

**What should happen:**

should hit for a few k instead of around 100 - 200 and ofc scale with attack power

**Comment by Anders98** [comment]
bump

**Comment by giles1508** [comment]
Bump indeed,  my poor bear is loosing like 2k dps lel

**Comment by Dranah** [comment]
Well, what I could find is that maul does not scale with level at all. It has a fixed base damage of 35, and the rest comes from attack power.
19% of your melee AP is converted to maul damage, supposedly.

Currently, the spell only considers your base attack power, nothing that items/spells/buffs add will account to any extra damage on maul. This needs fixing.
This castrates bear tanks quite alot and is high priority to fix.
How it should work: the spell should consider attack power gained from gear, buffs, etc.

**Comment by Keader** [comment]
```
Description: An attack that instantly deals ${35+$AP*0.19-1} physical damage$?s54811[, and an additional ${(35+$AP*0.19-1)*0.50} damage to a nearby target][].  Effects which increase Bleed damage also increase Maul damage.
```
Was not adding any AP at all.
Now it will scale with 19% of AttackPower.

**Comment by giles1508** [comment]
Just to check keader, have you set it so its damage is also increased when mangle is on the target? As you can see in the script you provided that anything that increases bleed damage increases maul damage,   and mangle does just that

**Comment by Dranah** [comment]
Hmmm. Just tested on PTR. Feels like the spell now does exactly 19% of AP as damage, no base damage and ignores armor.

**Comment by Keader** [comment]
What shit test you did?
I just changed spell coeff, nothing more change. It not ignore armor and basepoints is still there.

**Comment by Dranah** [comment]
I did a test on multiple lvl 85 tank n spank enemies in Twilight Highlands with standard armor.
I had 1100 attack power (almost naked toon) and my Maul was hitting for 210 damage continuously which is exactly 19% of it. 
Then my AP dropped to 900 (clicked off the vengeance buff), and the damage went down to 170ish, which is also exactly 19% of it.
Then I cast mangle on the target, and the damage of maul did not change at all. (it should have increased by 30% as bleed damage do)
Conclusion: There is no base damage added there clearly, and the damage is not reduced by armor. 
In comparison, my mangle was calculating to do 6200 damage unmitigated, but only hit target for 4,6k, as the armor affected it as intended.

**Comment by Keader** [comment]
new script pushed.

**Comment by Dranah** [comment]
The damage is off in the higher range now. It seems to be doing double the intended values, with rounding error considered.

Test results:
716 AP: damage expected=171 unmitigated -- actual= 341 unmitigated 
1460 AP: damage expected = 311 unmitigated -- actual = 623 unmitigated 
2248 AP: expected = 461 unmitigated -- actual = 923 unmitigated

Now here comes the interesting part:
This doubled damage value, only one half of it obeys bleed buffs, the other half doesn't seem to.
Seen similar issue before elsewhere...

But, the spell seems to properly obey armor now.
Note: The Raider's Training Dummy (boss lvl) has no armor whatsoever, about 1k according to NPC info. Therefore it's not a relevant test subject.
I've done my armored tests on Lord Marrowgar.
Unmitigated damage was recorded on critters with no armor. (yes i killed every damn squirrel in darnassus)

Bleeds:
It is affected by the bleed buff of Mangle now, however the math doesn't check out. Almost certainly related to the damage being doubled, because Mangle bleed buff is exactly half as effective as it should be.
It appears to boost one half of the damage dealt by 30% but not the other.

**Comment by Keader** [comment]
Check if is fixed.

**Comment by giles1508** [comment]
Hi dranah by any chance did you test with maul glyph on also as that causes maul to cleave an additional target for 50 % only reason I'm saying this here is because you might be able to kill 2 birds with 1 stone if it's not calculating the cleave tidy also

**Comment by Dranah** [comment]
There is no 2 bird with 1 stone on github. We fix 1 thing at once. If Glyph is broken as well, it will go in a separate report, separate fix.

**Comment by Dranah** [comment]
PS: there is no change.

**Comment by Dranah** [comment]
716 AP : expected=171, actual=226
1000 AP: expected = 225, actual= 278
2248 AP: expected =462, actual = 502
3260 AP: expected = 654, actual = 684
The values aren't sharp but is much closer. And the gap seems decreasing towards higher AP levels.

The spell respects armor, however bleed boost effects still don't apply to it.
Getting closer.

**Comment by Keader** [comment]
try now, bleed effect should work well now.

**Comment by Dranah** [comment]
Works, maul now benefits from bleed boost such as mangle. Still respects armor. Good enough.
