### ISSUE TITLE
[NPC] Mobus - AI

### ISSUE THREAD

**Issue by Rushor** [WoWManiaUK/Blackwing-Lair#2105]
Mobus requires spawn and scripting, 

https://de.wowhead.com/npc=50009/mobus

**Comment by Dranah** [comment]
The boss does way too low melee damage. 6-7k on cloth
He also non stop spams his Wake ability, which is dodgable, due to his giant hitbox being larger than its range, which makes him entirely useless. Wake should only hit behind him in the first place and he should melee and Ram the tank in the front.

Both ways, you can solo him right now.

**Comment by Rushor** [comment]
@Dranah do you now an other Boss where the: the behind mob - Part is working fine?

**Comment by Echinaceax** [comment]
@Rushor not sure of this atm rushor will ask test team

**Comment by Xman993** [comment]
@Rushor 

### Mobus Stats 
* HP: 12,883,800 Patch 4.1.0 , or Patch 4.0.3a (we Current at)  30,062,200
* Armor: 11,977 
* Damage: 58,403 - 86,705.

[Wiki link](https://wow.gamepedia.com/Mobus)

**Comment by Echinaceax** [comment]
Yes patch note only changed from 30m to 12m at 4.1

So Mobus should indeed be 30m (and **NOT** 12m) 

![4](https://user-images.githubusercontent.com/39439201/78273811-a1ef5f80-750f-11ea-9833-5e388e1614cd.jpg)

**Comment by Xman993** [comment]
#4351
