### ISSUE TITLE
[Item] Vicious 377 crafty

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2111]
**Links:**
http://prntscr.com/nuonuo

from WoWHead or our Armory
https://wow.gamepedia.com/Vicious_Embersilk_Cowl

**What is happening:**
All professions have 377 vicious gear to craft very easy
with just few stacks of cloth, ores leather, or gems, followed by couple volatiles, 377 items are crafted within a day or less for full set

**What should happen:**
items should not be available till very late patch 4.3 Hour of twilight

if someone have suggestion how to solve this, be free to comment
and to link id of all items that are 377 craftable

**Comment by giles1508** [comment]
crafting gear isnt an exploit ,  as its not a bug,   its just something that has been overlooked,  the same as buying epics from justice point vendors but that isnt bothering people,  farming instances that are not intended to drop loot is exploiting,  the tag on this needs changing tbh ,  and while it does need addressing,  so does the justice vendors selling epics as that also wasnt available until later patches,   to stop 1 thing you have to stop it all,  and i fear that until there are dungeons that are all open and scripted this is the only way players are able to quest and farm freely without having to worry about dying to packs of mobs due to lack of gear

**Comment by Frostmanx** [comment]
This issue is already reported, please make sure to check before posting 

https://github.com/WoWManiaUK/Blackwing-Lair/issues/1971

**Comment by TheSale** [comment]
Well I had talk today with one gm, and everything he said he was right.
Exploit is everything that make it easy.
410ilvl items are meant to be released in a year on our server, so pvp 377 crafting items should follow them.
you consider 359 pve item that drop from boss exploit, but pvp item that can be farmed in 15-30 min is not exploit and even higher item level?
That cheap and easy crafted item beat ALL normal cata dungones and most heroic ones
Only heroic dungeons that are comparable to this items are ZA, ZG, End Time and Hour of twilight.
All other dungeons on hc mode drop 346 rare item quality
It is even has higher item level of some raids that will be released soon.... Blackwing Descent drop 359 items in 10 and 25 man normal mode...
server will be progress but what is to progress when on day 1 when I hit 85 I go kill 50-100 humanoids and 50 elementals and I am good to go with my gear to next year....

So this is how will server look
![Untitled](https://user-images.githubusercontent.com/20323863/58530200-2e3d4180-81de-11e9-81d8-903ba5820544.jpg)

You want dungeons? Nope I have 377 items
Do you want HC maybe? are you doing END TIME? or Hour of Twilight? Nah just regular Deadmines!
Pfff naaaah you suck! I do only Those 2 I have 377!

Everyone will look the same, everybody will be the same.. And that gear will be ONLY option

**Comment by Dranah** [comment]
All 377 crafted gear used to be lvl 339 until the later patch.
The problem is real and has been reported before.
We should not debate whether this needs adjusting or not, the only question is how urgent it is to do so. (how big of priority)
Crafted pvp gear, despite its high item level is pure garbage for PVE, it has less PVE stats than a 333 PVE piece. It helps questing for sure , but taking a week or two to adjust the problem won't lead to irreversible damage on the server community. Unlike being able to buy out all the valor gear for JP... therefore the weight put on that one first.

**Comment by Kitzunu** [comment]
I will close this since it is marked as duplicate :)

**Comment by TheSale** [comment]
well I could not agree more that 377 crafted item is not that good in pve @Dranah 
it is like you using green item, and not rare. But newer the less, it still give more base stat(armor) than 346 ilvl, more primary stat (agi, int or str), more stamina, and higher affix, only downside is trading 1 affix for resilience. But people dont give crap about that, they will consider it as egual to 346 or even superior.

On wow mania, there is similar issue where people when hit lvl 80 rush to wintergrast, do week quests, play few wg battles and get enough honor to buy 2-3 items to boost their GS so they can go in RDF or pug raid, 264 pvp wrist cloak or neck are worst than 232 from FoS, PoS, HoR, but they still use it in pve because is easy to get. Lucky there are just 3 items 264 that you can get from honor points alone.

Here you can get full equipment 377, beside trinkets I think.
and people only look for this and care for nothing else
![Screenshot_26](https://user-images.githubusercontent.com/20323863/58547234-50978500-8207-11e9-899a-c57c7a6682ec.png)

and that will be so painful haha :D

For solution I would replace item with s9 crafted or give people that had items replacement ilvl 300 green items, so they can quest.. More we wait more people will have those items

@Kitzunu yeah you like closing issues the most, And it is good, as we all know it less issues we have that is better :)

**Comment by Kitzunu** [comment]
Well, why would I leave a duplicate issue opened? 

Add missing info to the original instead

**Comment by giles1508** [comment]
where your getting the idea that 15 minutes farming for full pvp gear is crazy,  for leather alone it takes well over a 1000 leather to make it all and buy the recipies,  plus the volatiles which drop rates suck...  and yes if your complaining about the pvp gear then you also need to take a look at the epics you bought for JP that wasnt available till a later patch again....   if your being technical both the PVP gear and the PVE gear needs to be changed

**Comment by Dranah** [comment]
Github isn't a place to argue who exploits more than the other.
The best solution would be indeed to downgrade/replace all the items to their 339 version and the recipes as well.
@TheSale What matters to me is how the gear affects the gameplay, not what people think about it. Nobody in their right mind will go raid in that crap, even in PVP it will be outdated very soon because epics have more stats. From this point of view, even if they stay in the game it won't change the giant picture at all.
