### ISSUE TITLE
[Spell/Shaman] Improved Lava Lash

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Blackwing-Lair#2120]
Implemented.
And implemented relation between Searing Flames and Lava Lash too

**Comment by Dranah** [comment]
Ok turns out nothing works about this, so i chose to reopen this instead.

1. Must increase Lava Lash damage by 20% per searing flames application - doesnt increase damage
2. Must consume the stacks in the process - doesn't consume stacks when LL is cast
3. Must spread Flame Shock to nearby targets - doesn't spread
Spell IDs:
Searing Flames Talent ID 77657
Searing Flame Stacking debuff effect spell ID 77661
Lava Lash spell ID 60103
Improved Lava Lash 77701

**Comment by Keader** [comment]
Someone forgot to send part of fix :D

**Comment by Imba232** [comment]
Still doesn't spread flame shock.

**Comment by Dranah** [comment]
Well, it does spread, but only if Searing flames are present to be consumed.
Fails to spread the Flame Shock if the target doesn't have any stacks of Searing Flames.

**Comment by Imba232** [comment]
It only spreads it sometimes, and Searing Totem doesn't attack the target focused by the shaman, the one with Stormstrike or Flame Shock, as it should. So spreading flame shock is just something of luck at the moment.

**Comment by Dranah** [comment]
Searing totem issue is in another thread.
Nonetheless , the talent is now fixed so it will always spread regardless. Timers are properly copied.
