### ISSUE TITLE
[Talent] Dancing Rune Weapon

### ISSUE THREAD

**Issue by Frostmanx** [WoWManiaUK/Blackwing-Lair#2132]
**Links:**  https://www.wowhead.com/spell=49028/dancing-rune-weapon

**What is happening:** When the talent is activated the weapon is summoned but it does not do anything and disappear afterwards.

**What should happen:** Summons a rune weapon for 12 sec that mirrors your melee attacks and bolsters your defenses.

While active, you gain 20% parry chance.

**Comment by Dranah** [comment]
The spell doesn't do the same thing as on LK....

**Comment by Holywinter** [comment]
Hey. Almost the same thing happens to me, but the weapon isn't even summoned. This is a critically neccesary ability for a Blood Death Knight..

**Comment by Slydee23** [comment]
can we get this fixxed for raid plsss ?

**Comment by Echinaceax** [comment]
@Keader Still an issue 16.12.19

**Comment by Echinaceax** [comment]
@mfranca0009 

tool tip 

![rune](https://user-images.githubusercontent.com/39439201/105921519-35fb5c00-6039-11eb-968a-2fbacf748cfd.jpg)

parry chance increased by 20 

![rune1](https://user-images.githubusercontent.com/39439201/105921559-414e8780-6039-11eb-8245-e1457ce1c845.jpg)

nothing from the rune weapon 

![rune2](https://user-images.githubusercontent.com/39439201/105921654-6d6a0880-6039-11eb-9ff9-94fc3fb18fdc.jpg)





**extra info** 
visually the rune weapon works (on PTR)

![rune6](https://user-images.githubusercontent.com/39439201/105922610-401e5a00-603b-11eb-828d-3a0093db3e49.jpg)

**Comment by mfranca0009** [comment]
Need more info on what melee attacks it should "mirror", if we can find this info. One WoWhead comment said it mirrors melee attacks like `Plague Strike`, `blood strike`, `heart strike`; need confirmation if this is accurate. @Echinaceax

**Comment by Echinaceax** [comment]
it mirrors the damage done by the DK _Plague Strike, blood strike, heart strike_  are the DKs main spells yes

will ask valk or Drache for their imput

**Comment by golosomie** [comment]
Dancing Rune Weapon didn't really change since Patch 3.2.0 .

[Patch 3.2.0 Patchnotes](https://wowwiki.fandom.com/wiki/Patch_3.2.0):
> Dancing Rune Weapon: The rune weapon will no longer cast Corpse Explosion.

[Patch 3.1.0 Patchnotes](https://wowwiki.fandom.com/wiki/Patch_3.1.0):
> Dancing Rune Weapon: [..] Attack speed of pet increased from 2.0 to 3.5. [..]
> Dancing Rune Weapon: [..] it will now only echo death knight spells whose primary purpose is dealing damage. [..]


From what I've found, all spells that require a weapon, melee range and have the primary purpose of dealing damage (excluding Corpse Explosion) should be mirrored. The pet should only mirror your autohit damage, but have a fixed attack speed of 3.5.

I'll update this with a list of possible spells in a minute. 
Plague Strike is irrelevant because you can't have it when specced into Blood dk

**Comment by golosomie** [comment]
@mfranca0009 

Blood Strike 	 (SpellID 45902)
Death Strike 	 (SpellID 49998)
Heart Strike 	 (SpellID 55050)
Festering Strike (SpellID 85948)
Obliterate	 (SpellID 49020)
Rune Strike 	 (SpellID 56815)
Necrotic Strike   (SpellID 73975)
Plague Strike 	 (SpellID 45462)

[45902, 49998, 55050, 85948, 49020, 56815, 73975, 45462]

**Comment by mfranca0009** [comment]
Thank you @golosomie 

Will look into this shortly

**Comment by mfranca0009** [comment]
In the middle of working on this.

- [x] Base attack speed is set to 3.5 seconds.
- [x] Now attacks enemy when player is in combat.  
- [x] Should mirror player's DK spell casts for spells listed above by @golosomie
- [x] Should mirror auto-attack damage done by player to current victim.

**Comment by mfranca0009** [comment]
All set, instead of mirroring auto-attack damage, I made the Rune Weapon share the same min / max damage as the player does which will let the Rune Weapon auto-attack with the same damage range as the player would; basically scaling the "pet" to player's damage.

Actually mirroring the auto-attack damage exactly as the player damage, similar to mirroring the spells, doesn't seem to be possible with what we have with current core functionality.

Should be all set at this point 👍
