### ISSUE TITLE
[Spell] Death Knight Rune Strike

### ISSUE THREAD

**Issue by kurabawa** [WoWManiaUK/Blackwing-Lair#2133]
**Links:**

from WoWHead or our Armory

**What is happening:**

Rune Strike can only be used 10 seconds after dodge/parry in blood presence.

**What should happen:**

Rune Strike should be able to be used at all times in blood presence and not only after parrying/dodging.

**Comment by Frostmanx** [comment]
Confirmed. 
https://www.wowhead.com/spell=210764/rune-strike

**Comment by giles1508** [comment]
Will need a link to a more outdated spell link,  that spell has changed a lot, the current one is updated for bfa,  I'll try and find a link to cata version now,  but I'm not at home

**Comment by giles1508** [comment]
https://wow.gamepedia.com/Rune_Strike

**Comment by giles1508** [comment]
There is the cata version which shows in the changelog that in 4.0.3 it was indeed changed to be used all the time when u have runic power for 160%
Aslong as the dk is in blood presence

**Comment by Frostmanx** [comment]
Patch 4.0.3a (2010-11-23): Rune Strike will not require a dodge or parry to activate as long as the Death Knight is in Blood Presence.

**Comment by Dranah** [comment]
This is still not working right.
Entering blood presence properly enables you to runestrike without needing to dodge/parry.
However, when the DK dodge/parry an attack and it triggers runestrike the old fashioned way, on top of being in blood presence, when the effect expires, the rune strike becomes unavailable again, despite still being in blood presence.
Swapping to frost pres and back, makes you able to use it again, but this is not realistic to keep doing in order to re-enable the spell while tanking.

How it should work: Dodging/parrying an attack giving you a rune strike! proc, should not overwrite the availability via blood presence. The spell should not turn off and be unusable until you either reactivate presence or get another proc via dodge/parry.
