### ISSUE TITLE
[Quest] Into the Realm of Shadows -12687- Blocks DK chain!!

### ISSUE THREAD

**Issue by slaniaxx** [WoWManiaUK/Blackwing-Lair#216]
During the Death Knight starting zone quest "Into the Realm of Shadows", after killing the required NPC (28768) and mounting the deathcharger(28901) , the player will randomly lose control of the deathcharger and sometimes won't be able to take it back thus rendering the quest unfinishable. During these losses of control, the deathcharger will move randomly.

Workaround: After each loss of control, the player can dismount and remount the vehicle/horse to regain control.

Note: Sometimes while dismounting player's action bars can disappear or player can fall through the map and die.  /reload fixes the issue.

Quest ID : 12687

**Comment by Dranah** [comment]
Additionally, the entire phasing doesn't work.
You should be phased into the realm of shadows , and the riders of acherus should only be visible there.
This part is missing entirely, you're not phased and the objectives are spawned in the normal phase.
It's a cosmetic issue, but need be fixed someday.

**Comment by Dranah** [comment]
This quest is now entirely broken.
The phasing is messed up. Your quest objectives are in the living phase, making you unable to see or attack any of them since youre phased into the shadow realm.
Killing these npcs in the living phase does not give you a horse, their horse is untargetable and simply walks away after the rider is killed.
This quest cannot be completed now and is blocking the chain...

How it should work:
https://www.wowhead.com/npc=28909/dark-rider-of-acherus should be present in the "realm of shadows" phase, not the regular one
This is the aura that phases you to the realm of shadows: 52693
This puts you into phase "174" this is where the riders must also be.
The horse which currently spawns when u kill rider is ID 28782 which is an elite that cannot be mounted
The horse we need is this https://www.wowhead.com/npc=28302/acherus-deathcharger
It needs to be mountable if you mouse over it and click it
Vid: https://www.youtube.com/watch?v=GS2WP5TH4dk
