### ISSUE TITLE
[Object] Door Stratholme

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#2173]
**Links:**
https://www.wowhead.com/stratholme
**What is happening:**
The door is not opening (Locked) even with key
**What should happen:**
The door should open after you kill https://www.wowhead.com/npc=10435/magistrate-barthilas#drops

**Comment by Echinaceax** [comment]
GM told me this needs attention @Rushor 
ive got SS from GM where the issue is as GM couldnt assist either

![stratholme](https://user-images.githubusercontent.com/39439201/65389803-f98b6200-dd59-11e9-8434-9755349c4ccf.jpg)
![gate locked](https://user-images.githubusercontent.com/39439201/65389807-fd1ee900-dd59-11e9-9fe5-1f82dc7d34e2.jpg)

**Comment by Rushor** [comment]
can be opened now

![I](https://i.imgur.com/3PDnfCz.jpg)
