### ISSUE TITLE
[Spell] Infected bite - ID 49861 - Debuff with very high damage - Borean Tundra

### ISSUE THREAD

**Issue by zippoking** [WoWManiaUK/Blackwing-Lair#2376]
**Links:**
Spell: https://www.wowhead.com/spell=49861/infected-bite
NPC: https://www.wowhead.com/npc=25650/plagued-scavenger
for Quest:  https://www.wowhead.com/quest=11903/its-time-for-action

**What is happening:**
When i got the dot on this server, it took 1161 - 1333 damage every 2 seconds, which is almost 3 times the damage than from videos i saw. The duration of the buff is 8 seconds, which means the tick applies 4 times, which means almost 5000 damage. Additionally when you are fighting a couple of mobs, then this damage can easily kill you, especially when playing a class that doesn´t have heal spells.

![Infected Bite - how it is](https://user-images.githubusercontent.com/18005338/59424319-1071fe00-8dd4-11e9-811f-5e477a072dfb.png)

**What should happen:**
In 3 videos i saw, that the dot takes about 380-450 damage every 2 seconds from the player. Which seems to be a good amount, since there is no chance that you die from the dot.

![Infected Bite - how it should be 2](https://user-images.githubusercontent.com/18005338/59424316-1071fe00-8dd4-11e9-94f0-ce6c85b0f9e3.png)
![Infected Bite - how it should be 3](https://user-images.githubusercontent.com/18005338/59424317-1071fe00-8dd4-11e9-9a53-4753010abcd4.png)

![Infected Bite - how it should be 1](https://user-images.githubusercontent.com/18005338/59424320-1071fe00-8dd4-11e9-8527-33d01f4b7d95.png)

**Comment by Dranah** [comment]
This is not a class spell but a world NPC one.

**Comment by Echinaceax** [comment]
> This is not a class spell but a world NPC one.

Guess new label is in order so that testers don't get confused with class player spell and npc spell lol 
though NPCs are classes too right ?

**Comment by bagi84** [comment]
Not being funny but this is getting silly more labels a spells a spell next wel have npc, rare npc, world boss npc, major city npc, dungeon npc, quest npc, class spells, World boss spells, npc spells, raid boss spells, scroll spells... Where will the madness end 😂

**Comment by Dranah** [comment]
NPCs aren't classes. There are 10 character classes, playable by players. Class label is for issues with their spells and mechanics.
We're fixing those issues with keader as priority and if I find a report that absolutely doesn't belong there, i'll remove the god damn label so it doesnt keep popping up in my filtered search.
Not everything needs a label other than confirm/fixed labels. There is no need to make a new label each time you can't find a label fitting a single report.
Labels serve a purpose to ease our job when filtering issues and if you keep labeling reports without a sense because you don't understand basic WoW terminology (such as what CLASS means) then it makes our job harder. 
If you get butthurt over me pointing this out over and over, it's not my fucking problem, i'm done arguing over blatant bullshit like labels. If your labels make no sense, i'll remove or delete them.

**Comment by gitkulu** [comment]
Not being funny but you could use a little more class.

**Comment by Rushor** [comment]
fixed. bonus removed

![I](https://i.imgur.com/v0B52bH.jpg)
