### ISSUE TITLE
[Quest=26361] Smoot's Samophlange - Azshara

### ISSUE THREAD

**Issue by Absaggio** [WoWManiaUK/Blackwing-Lair#2378]
https://www.wowhead.com/quest=26361/smoots-samophlange

What is happening:
When i click on the NPC Smoot nothing happens.

What should happen:
When i click on the NPC he should be stunned and drop "Induction Samophlange" (item id=58224) to complete the quest.

**Comment by giles1508** [comment]
ok so this quest,  should not even be available to do yet,   as the chains before it are still broke,  so this is why this is broke...  most likely due to not being in the right phase,    this is 2 chains ahead of the weapons of mass dysfuntion quest,  which to my knowledge is still broken ?   as there has been no fix label on the github report,   if someone could let me know that would be brill so i can test it further

**Comment by giles1508** [comment]
and also could you please say how you even managed to get this quest ?

**Comment by Absaggio** [comment]
GM completed the quest "Weapon of mass dysfuction" for me becouse the command .bq doesn't work

**Comment by Rushor** [comment]
okay todo: add pathing for Smoot, once Smoot is klicked and quest is active > let the gameobject spawn.
