### ISSUE TITLE
[Zone] Gates of Sothann

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#241]
On the map in Mount Hyjal the gates of Sothann the map displays a flight path. However there isn't one here. But this link of wow head says the area no longer exists https://www.wowhead.com/zones?notFound=4998&assumedName=Gates+Of+Sothann
![world of warcraft 20_12_2018 17_52_43](https://user-images.githubusercontent.com/42302580/50301978-9e51d980-0480-11e9-9ce0-f1ee7d7ded27.png)
![world of warcraft 20_12_2018 17_52_35](https://user-images.githubusercontent.com/42302580/50301982-a01b9d00-0480-11e9-85bf-6840268bd6cd.png)

**Comment by Dranah** [comment]
It was removed from the game sometime later since Wowhead is updated to BFA right now.

For as far as I could find, this area had phasing issues on retail too, so that the NPCs are there, but you cannot see them.
This may have something to do with the reported NPC https://github.com/WoWManiaUK/Blackwing-Lair/issues/243 as you would pick up a quest chain that supposedly affects this area too (retail players have reported needing a specific quest completed or in your log to be properly phased at the Gates)
