### ISSUE TITLE
[Spell/Shaman] Searing Totem (issue 2) 

### ISSUE THREAD

**Issue by Imba232** [WoWManiaUK/Blackwing-Lair#2410]
**Links:**

https://www.wowhead.com/spell=39591/searing-totem

**What is happening:**

Searing Totem is attacking randomly and also starts attacking if any enemy npc is in it's range.

**What should happen:**

Searing Totem should "assist" the shaman and always attack it's target. It should not start attacking by itself.

**Comment by TheSale** [comment]
I am not sure about that, searing totem could always ninja pull, just it should focus target with flame shock, and not switching to target whenever you switch target to assist you, but it should never attack neutral mobs without being in combat with that mob since they are not consider enemies.

"Summons a Searing Totem at your feet for 1 min that repeatedly attacks an enemy within 0 to 20 yards, dealing Fire damage."

**Comment by Dranah** [comment]
Spell ID 3599
NPC ID 2523

1) It is capable of pulling mob packs apart. Searing totem tagging a mob will cause other nearby mobs to ignore group-aggro, and therefore shamans can use this to separate mob packs that would be otherwise difficult to handle. This is not intended.
**How it should work:** When Searing totem attacks a nearby mob that is part of a mob pack, the entire pack should aggro, just like when a player spell pulls them.
2) Target priority
"The totem will prefer to attack enemies that are afflicted by your Flame Shock or Stormstrike effect."
It does not attack neutral mobs, only red ones (enemies). It does not have any restriction towards needing to assist the shaman or not ninjapull when you arent in combat.
However the totem does not currently have this attack priority working, it will shoot closest target instead.
**How it should work:** The totem should prioritize targets afflicted by either flame shock or stormstrike, over those that do not have any of these effects.
