### ISSUE TITLE
[Priest][Talent] Pain and Suffering

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2477]
**Links:**

47581 ID

**What is happening:**
Talent does not reduce dmg taken from Shadow word: death

**What should happen:**
Talent should reduce damage taken from SWD accordingly.

**Comment by Dranah** [comment]
No change. 
Must note also that the self damage from SWD is completely off the scaling by default.
1) It seems to double dip some mods so it does more damage to you than it did to the target. 
2) It also doesn't scale with crit in a sense that when the SWD does double damage due to critting, the retaliation still calculates from its base damage.

**Comment by Keader** [comment]
i cant make it scale with crit.
Because crit happens after hook is called :(
But fixed double dip issue.
