### ISSUE TITLE
[Spell] Flame Orb - ID 82731

### ISSUE THREAD

**Issue by Cenasty** [WoWManiaUK/Blackwing-Lair#2505]
**Links:** https://wow.gamepedia.com/Flame_Orb

**What is happening:**

Flame orb explode after 5 seconds, whether if it has found a target or not.
If it doesn't have found a target, it will continue in it's original path then explode
If it does have found a target, Flame orb will slow down, attack for a few second then explode.

**What should happen:**

Case 1 : No target in a line for 40 yards. Flame Orb should seek a target until it reach it's 40 yards' limit range then explode
Case 2 : Target at any meter between the spot where it has been cast and 40 yards.
Slow down (or stop I'm not sure about this one) near the target, attack for 15 secondes then explode

**Comment by Dranah** [comment]
Cannot reproduce issue. It properly attacks for 15seconds before exploding.

**Comment by Cenasty** [comment]
I had it issue yesterday again (I mean eveytime I try to use it but not on dummies)

Seems like being already in combat (throne of tides or vortex thing, in uldum, can't remember name right now) make it bug. Il last 5 second then explode.

**Comment by Priestelar** [comment]
Edit: This is still a problem with this, I managed to reproduce it here is the video of it:

https://youtu.be/DHrK8I5ykJw

some things to note about this reproduce: it was working on the training dummies, it was working on normal mobs in twilight highlands but when we went into this dungeon to test it as well because i know sometimes dungeons cause bugs and it exploded after 5 seconds 2/3 times so it is a bug that DOES indeed happen and we managed to get it on film.

**Comment by sarahkay88** [comment]
Iv notice that on a few occasion when cast I'd doesn't move n just stays in front of me.

**Comment by Rushor** [comment]
oh it was already assigned
