### ISSUE TITLE
[Priest] Mind Sear (issue 2)

### ISSUE THREAD

**Issue by Grotesqueee** [WoWManiaUK/Blackwing-Lair#2514]
**Links:**

spell id 48045

**What is happening:**
Damage is lower than intended, according to DrDamage.
Average tick is ~2500

**What should happen:**
(1.311/5)*6966 with 15% shadow damage from passive + 6%  dmg increase from Twin Disciplines talent (47588) should make an average of 3069 dmg per tick.

**Comment by Echinaceax** [comment]
Have you tested it with and without this particular addon?

try a different dmg/heal meter see if you get same results

**Comment by Keader** [comment]
This is my Dr Damage screenshot.

![image](https://user-images.githubusercontent.com/7120913/67388922-f6111380-f56f-11e9-9dd8-1aa14b117b91.png)

If you read Hit part, it says with my talents and my spellpower, it should hit 5 x something around 2159
In same screenshot, you can see that my damage was 2162, inside of avarage range.
A lot of stuffs changed since 22 jun (when this issue was reported), so in our current state, it's fixed.
