### ISSUE TITLE
[Npc] Akma´hat 

### ISSUE THREAD

**Issue by dagget1337** [WoWManiaUK/Blackwing-Lair#2527]
**What is happening:**
I know there is already an issue about the Npc/Worldboss Akma´hat, but this is about his generic stats which make him somehow too easy to kill, his spawn time seems to be around 24h and he´s oddly so weak that a 85 Deathknight can solo him, which is probably the problem why he´s dead everyday, well you may think why hes dead everyday when his spawntime is only 24h? Ofc its around 2:00-3:00 PM because everyday i checked on him hes either dead, or some1 is fighting him, like today a 85 Horde DK just soloed him.

**What should happen:**
It seems that he´s not just any Rare mob which should be Soloable with such a short respawn time but more like a Worldboss, so his stats should be increased as such to make him atleast 5 or 10 manable. If he should be as strong as he is rn than this is just a joke with his 12mil hp.

**Comment by Dranah** [comment]
NPC ID 50063 
This guy seem to be melee'ing around 2k damage, occasionally he casts a shockwave that hits 80k on cloth, but probably just tickles on a DK.
Some of his abilities dont work and he's generally just too weak.
He currently drops lvl 359 epic loot so this need to be addressed asap.

**Comment by Dranah** [comment]
More info:
1)Spawn time :
Like all world bosses in cata he is on a '72hr chance of spawning' which basically means, since he shares his spawner with the other bosses, there is a chance he will spawn after he dies every 72hrs. 
2) Abilities:
https://www.wowhead.com/spell=93561/stone-mantle - missing atm-
https://www.wowhead.com/spell=94946/fury-of-the-sands - casts it but doesn't do anything at all
https://www.wowhead.com/spell=94968/shockwave - does proper damage but doesn't stun
3) Melee damage
Approx 70-80k base, he is swinging for 30-40k on tanks on videos:
https://www.youtube.com/watch?v=MiWgvYmXkqk

**Comment by Rushor** [comment]
respawntimer is already set to 72 hours

**Comment by Rushor** [comment]
basedamage increased please check that for now :)

**Comment by Rushor** [comment]
SPELL_STONE_MANTLE added. will cast it the first time after 21000 ms and then every 90000 seconds

**Comment by Dranah** [comment]
Looks much better.
