### ISSUE TITLE
[Spell=55342] Mirror Image - Mage

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2626]
**Links:**
https://www.wowhead.com/spell=55342/mirror-image
from WoWHead

**What is happening:**
The copies spawns and attack the enemies but they generate no threat on them.

**What should happen:**
The copies should generate threat and pull mobs out from the caster.

**Comment by Cenasty** [comment]
On WotLK Mirror Image cancel our whole threat for the whole duration of the spell (when there is someone else in threat's list)
While, it should work Author said.

(I don't have any OmenThreatMeter to try it out, but I wanted to give a little bit more detail to the thread. I don't think mechanic has changed between WotLK and Cataclysm, otherwise mb)
