### ISSUE TITLE
[Quest] Deepholm, Realm of Earth - ID 27123 - Deepholm

### ISSUE THREAD

**Issue by HrPottemager** [WoWManiaUK/Blackwing-Lair#2630]
Quest - https://www.wowhead.com/quest=27123/deepholm-realm-of-earth
NPC - https://www.wowhead.com/npc=45042/thrall

What is happening:
Jump on Aggra's Wyvern and fly into the breach at the Maelstrom. Once you're on the other side, speak to Maruut Stonebinder.

What should happen:
There should be a Wyrven behind Agera that you can jump on that will fly you through the rift.

**Comment by Zygersaf** [comment]
Just to add to this issue, the above poster neglected to mention that the Wyvern is not there to be able to jump on. 
Additionally, in an attempt to workaround this issue manually, I went back to a major city (SW) and took the portal to Deepholm, and when doing so I have been phased to where there are no NPCs in the temple of earth to be able to continue the quest line.

**Comment by zippoking** [comment]
**How it is:**
![Deepholm Realm of earth - how it is](https://user-images.githubusercontent.com/18005338/61039532-3a1c4600-a3cf-11e9-9720-59d3099a2f39.png)

**How it should be:**
![Deepholm Realm of earth - how it should be](https://user-images.githubusercontent.com/18005338/61039531-3a1c4600-a3cf-11e9-9ab8-2e6add31679b.png)

**Comment by Sammy974** [comment]
@Rushor  any chance to fix that? :)

**Comment by Rushor** [comment]
it's a hard quest script

**Comment by zippoking** [comment]
The way it works is, that the player hops onto the Wyvern and flys into deepholm. Somewhere within this script the players is in the correct phase to accept all quests in deepholm.

Instead of flying the player into deepholm, we  can just use the normal teleport. The problem is that the player is in wrong phase. But the question mark is on the minimap.

So as soon as the player accepts the quest "Deepholm, Realm of Earth" you need to put him into the correct phase, that he can turn in the quest.
The NPC which can´t be seen at the moment is: https://www.wowhead.com/npc=43065/maruut-stonebinder

Hope thats understable :-D
![Deepholm Realm of earth - how it is 2](https://user-images.githubusercontent.com/18005338/61530596-d1634800-aa24-11e9-8d60-cafd8bde5fd8.png)

**Comment by zippoking** [comment]
The NPC´s are available in Deepholm now. 
So you can complete the quest and continue with the quest chain.

**Comment by gamer100** [comment]
the phase issue is  still at the  wyvern but after using portal to deepholm you can deliver the  quest and the  quest  npc's are available

**Comment by Eirolla** [comment]
Suggestion: After you get this quest, there's should be a portal to Deepholm for not waste ppl's time with use mall stone/hearthstone.

**Comment by Randomplayerx** [comment]
still not working.
https://ibb.co/GQVBwCR

**Comment by Echinaceax** [comment]
Still not working 27.11.19

**Comment by Rushor** [comment]
I will fix this in an other issue about deepholm. Do Not worry
