### ISSUE TITLE
[Spell] Priest Healing Spells

### ISSUE THREAD

**Issue by hordetester** [WoWManiaUK/Blackwing-Lair#2636]
Links:https://www.wowhead.com/spell=17137/flash-heal
https://www.wowhead.com/spell=2060/heal
https://www.wowhead.com/spell=62334/greater-heal

I think there's something wierd about priest healing spells. To start off, the spells Heal, Flahs Heal and Greater Heal: Flash Heal is healing for 10874 (5765 mana usage), Heal is healing for 5434 (1953 mana usage) and Greater heal is healing for 14499(5559 mana usage). To me it seems that those spells are being used like in different spell ranks (something that people told me that doesn't happen in cataclysm). Also skills like Prayer of Healer, Prayer of Mending, Penance and others seems to be healing less than they should. It could be me just being paranoid and talking something idk cause i never played cata, but these spells are really looking weird to me. I'd really appreciate if u could double check priest healing spells .

**Comment by Tatoepaladin** [comment]
thos links are to Bfa wow and not Cataclysm

**Comment by Rushor** [comment]
could you correct the links then?

**Comment by Dranah** [comment]
One spell, one issue please. Nearly all spell coefficients are wrong atm, so chances are all of them needs a correction.

However, your base idea of how cataclysm healing spells work is a little flawed. There are no spell ranks anymore, however the game was redesigned to make healing more challenging, providing you with multiple tools to adapt to multiple situations rather than spam the very same spell over and over during the whole encounter. 
Heal is a weak, slow, but low cost spell that you should spam whenever there's no stress, while Flash heal is a quick, effective, yet costly ability for urgent spot healing. Greater heal is both effective and efficient cost-wise, but not quite quick enough to use in emergency.
Every healing spec was given a set of matching abilities, and this is their intended use.

**Comment by Rushor** [comment]
added for those spells

(63544, 'Priest - Empowered Renew');
(73510, 'Priest - Mind Spike');
(34914, 'priest- vampiric touch');
(589, 'priest- shadow word pain');
(34433, 'Priest - Shadowfiend');
(8092, 'priest- mind blast');
(33619, 'Priest - Reflective Shield');
(2050, 'Priest - Heal');
(2060, 'Priest - Greater Heal');
(17, 'Priest - Power Word: Shield');
(7001, 'Priest - Lightwell Renew');
(47750, 'Priest - Penance Heal (Rank 1)');
(47666, 'Priest - Penance Hurt (Rank 1)');
(27813, 'Priest - Blessed Recovery Rank 1');
(2061, 'Priest - Flash Heal');
(14914, 'Priest - Holy Fire');
(23455, 'Priest - Holy Nova Heal Rank 1');
(15237, 'Priest - Holy Nova Damage');
(49821, 'Priest - Mind Sear Trigger Rank 1');
(15407, 'priest- mind flay');
(8129, 'Priest - Mana Burn');
(63675, 'Priest - Improved Devouring Plague');
(64844, 'Priest - Divine Hymn');
(33110, 'Priest - Prayer of Mending');
(32546, 'Priest - Binding Heal');
(2944, 'priest- devouring plague');
(19236, 'Priest - Desperate Prayer');
(34861, 'Priest - Circle of Healing');
(56131, 'Priest - Glyph of Dispel Magic');
(56160, 'Priest - Glyph of Power Word: Shield');
(56161, 'Priest - Glyph of Prayer of Healing');
(64085, 'Priest - Vampiric Touch (Dispelled)');
(596, 'Priest - Prayer of Healing');
(139, 'Priest - Renew');
(70772, 'Item - Priest T10 Healer 2P Bonus');
(26170, 'Oracular Heal (Priest AQ Set 3pc Bonus)');
(59544, 'Priest - Gift of the Naaru');
(88684, 'Priest - Holy Word: Serenity');
(88686, 'Priest - Holy Word: Sanctuary');
(48045, 'priest- mind sear');
(32379, 'priest- shadow word death');
(585, 'priest- smite');
(81751, 'Priest - Atonement');


if anything is missing, p,s open a new report
