### ISSUE TITLE
[spell] druid stampeding roar (while prowling)

### ISSUE THREAD

**Issue by TheSale** [WoWManiaUK/Blackwing-Lair#2652]
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=77761/stampeding-roar
https://wowwiki.fandom.com/wiki/Prowl_(druid_ability)

**What is happening:**
speed is increased from 91% to 112%

**What should happen:**
it should be 60% bonus

**Comment by giles1508** [comment]
Please note that the figures above are with the optional talent called feral swiftness taken, if its not taken then prowl speed is 70 % so with stampeding roar it would be 130%

**Comment by TheSale** [comment]
normal speed 100-prowls speed 30= 70 + SR 60 = 130
feral swiftness 130-prowls speed 30= 100 + stampeeding roar 60 = 160

**Comment by Dranah** [comment]
Speed bonuses from spells and talents are multiplicative, not additive.
I.eg. while a Mount ADDS 60% movement speed, making your base 100% speed become 160, or 100+100=200% with swift ground mount,
spells such as Crusader Aura multiplies movement by 20%, if you had 200% movement speed with a 100% mount, that will be 200 x 1,2 = 240 after Crus aura, not 200+20=220.
All the movement bonus spells n talents work like Crusader aura, they multiply your movement speed, not add to it.
Your 70% stealthed speed becomes 91% with feral swiftness because 70 x 1,3 = 91%.
From the other direction, Prowl itself is not a fixed 30% to add or take, but takes 30% of whatever current speed you have, so it'd calculate as 130 - (0,3x130) = 91%. Results same.
Stampeding Roar increases the 70% stealthed speed by 60%, making it 70 x 1,6 = 112%.
It appears that the two effects do not currently stack, and i am not sure if this is a problem, most movement effects do not stack (dash does not, either)
Do you have any proof that they should stack?

**Comment by Dranah** [comment]
Same issue as the other. I'll ref this one.
