### ISSUE TITLE
[Npc] Restless Soldier - ID 46825 - Tol Barad

### ISSUE THREAD

**Issue by Sammy974** [WoWManiaUK/Blackwing-Lair#2752]
**Links:**
https://www.wowhead.com/npc=46825/restless-soldier#abilities
from WoWHead or our Armory

**What is happening:**
The Thunder Clap ability of this npc decrease too much the attack speed of his enemy. Tested with a rogue: the haste rating is decreased from a base of 8,74% to -83,96% and the energy grows up too slowly. It definitely slows up too much. Tested with a dk as well.

**What should happen:**
https://www.wowhead.com/spell=81140/thunderclap
Inflicts Nature damage to nearby enemies, increasing the time between their attacks by 33% and slowing their movement speed for 6 sec.

**Comment by Rushor** [comment]
spell adjusted

**Comment by Denrunmt** [comment]
The problem still persists. Thunder clap's npc decreases the attack speed of his enemy too much again. Please investigate.

**Comment by Rushor** [comment]
okay removed from all for now (affected spell: http://cata.cavernoftime.com/spell=81140)

**Comment by Cenasty** [comment]
Same problem happens when you attack the NPC 'Keep Lord Farson' in Farson Hold, Tol Barad Peninsula)

His spell decreased our energy refill rate

Before :
https://puu.sh/E74k1/604d371f7d.png
While affected by the spell :
https://puu.sh/E74k6/860492e608.png

Spell : 
https://puu.sh/E74kn/13bf476b18.png
