### ISSUE TITLE
[Ability/Mastery] Blood Death Knight - Death Strike

### ISSUE THREAD

**Issue by Z4but0m** [WoWManiaUK/Blackwing-Lair#3014]
**Links:**
https://cata-twinhead.twinstar.cz/?spell=49998
https://cata-twinhead.twinstar.cz/?spell=77513

**What is happening:**
Death Strike's healing and shield seems far too low and their dynamic effect, or the healing & shield that should be added or removed depending on how much damage the deathknight takes, seems to be too steep or too unchanging.

**What should happen:**
Death Strike's heal and the resulting shield should change more dynamically, depending on how much damage the Death Knight takes.

**Comment by kDracku** [comment]
Look my healing overall in deadmines HC https://imgur.com/5VlnOVR , i can solo survive a full pack of 5-6 mobs. And about the treath generation cant find anymore the topic. I can easly tank entire packs of 7-8 mobs without lossing aggro

**Comment by Sammy974** [comment]
The healing provided from Death Strike is always the same. 17214 in my case.
There's another important thing to check about Death Strike:

https://wowwiki.fandom.com/wiki/Death_Strike

" Patch 4.3.0 (29-Nov-2011): Death Strike now heals the death knight whether or not the attack misses, or is dodged/parried. As a result of this change, Death Strike no longer refunds its rune cost if it fails to hit the target, as the death knight will still receive the healing effect."

This is not happening. If your Death Strike doesn't hit the target because it's missed, parried or dodged, you get no heal and the blood shield is not refreshed.

**Comment by Randomplayerx** [comment]
The heal of DS is dependent on damage taken you every 5 seconds. Read the link.

If I am correct, the healing value resets every 5 seconds.

The absorb is depend on Mastery it doesnt change/barely changes. unless you have proc Mastery trinket like Vortex.

The other thing I saw on this issue is healing caused by Fallen Crusader runeforging enchant.

Also the DS healing should work with Vampiric Blood

Also [not tested] worms can die and not healing.

**Comment by Keader** [comment]
How it's scripted:

we have 5 spaces to save damage

[0] [0] [0] [0] [0]

If you take 1300 of damage, it will be:

[1300] [0] [0] [0] [0]

Each 1 sec, the core will move the damage to next space, so in next secound it will be:

[0] [1300] [0] [0] [0]

It means that: if you take 10 damages at same time, it will save only the last one.
Other thing, if you stop take damage, your last damage in each second will still move to next space.
When it reach the last space, the 1300 will vanish and everything will reset again.
But if you take:

1300, 1200, 1500, 1800, 1900, it will become:

[1300] [1200] [1500] [1800] [1900]

So when we calculate the heal, it will sum all damage and check
if damage taken is below 7% health, value chosen is 7% of your max health
if damage taken is high then 7% health, value chosen is damage taken.

Everything looks correct to me here, tell me if you find any specific problem.

**Comment by Keader** [comment]
This internal "1 sec" cooldown looks wrong to me '-'

**Comment by Keader** [comment]
Now it will take all damages, not each 1 sec.
So if you took 7 damages at same time, it will get the last 5 ones, instead just one (like old script)
