### ISSUE TITLE
Blood Death Knight - Threat Generation

### ISSUE THREAD

**Issue by Z4but0m** [WoWManiaUK/Blackwing-Lair#3019]
**Links:**
https://cata-twinhead.twinstar.cz/?spell=48263
https://cata-twinhead.twinstar.cz/?spell=84839

**What is happening:**
Blood Death Knight's threat generation seems to be very lacking, with many damage-dealing classes capable of taking threat away from them in group and single target situations in mere moments, despite the Death Knight's constant attempts to keep threat with AoE abilities like Blood Boil, Heart Strike and Death & Decay; in some cases, even taunting is ineffective.

**What should happen:**
The Blood Deathknight should be able, as all other tanking classes/specializations, to acquire and maintain aggro easily given the tools at their disposal.

**Comment by kDracku** [comment]
I personal not see any BDKs in heroics having problem with aggro , blood dk is like feral tank , you need to do dmg in order to mantain big treath. The rest of classes are easy to maintain aggro . Me as prot pala and feral tank i dont have any issue holding aggro even on high burst. I still leaveling my dk , i will come back with a comment about treath managing

**Comment by Z4but0m** [comment]
I have been noticing issues with threat, even in situations where I am dealing consistent damage like placing down a Death and Decay, spreading diseases and following with my AoE rotation. If other Blood death knights could come forward and talk of their own experiences, it would better help with this issue.

**Comment by Sammy974** [comment]
In my experience is true that if the dps start doing dmg too early in a pull, is hard to keep aggro with d&d, blood boil and spreading disease, because you need 4 gcd to do that (including Outbreak) and the treath generated in this way is not the best you can get, because a dps's aoe dmg will be stronger than yours. But if you use Heart Strike you should be able to get and keep aggro at least on 3 targets. Starting with full aoe rotation should work if the dps give you the time to do the entire aoe rotation before to do high dmg.  Heart Strike will help you to get high threat, expecially if you have the time to spread the diseases first. Otherwise, it will help you to take back the aggro if some mob escape. Try using it earlier and let me know.

**Comment by Keader** [comment]
Re-open this issue when you have sure that have something wrong.
