### ISSUE TITLE
[Dungeon] Black Morass

### ISSUE THREAD

**Issue by kDracku** [WoWManiaUK/Blackwing-Lair#3089]
**What is happening:**
I cant enter Black Morass even after i complete Return of Andormu (https://www.wowhead.com/quest=10285/return-to-andormu). Got the fallowing quest The Black Morass (https://imgur.com/yPknIzV) - https://www.wowhead.com/quest=10296/the-black-morass but i still cant enter. It says i need to complete Return of Andormu before i enter.
**What should happen:**
After completing Return of Andormu you get The Black Morass and can enter into the Black Morass

**Comment by Denrunmt** [comment]
For me Erozion doesn't even have the quest "Return to Andormu".

**Comment by Denrunmt** [comment]
1st - On what difficulty did you do Old Hillsbrad in order to finish the quests before getting to the quest "Return to Andormu". 
2nd - How did you complete the quest "Return to Andormu" ? Erozion won't give it to me.
3rd - Can you screenshot the message you get when trying to enter The Black Morass ?

**Comment by kDracku** [comment]
1 - HC
2 - For me it gived the quest
3 - https://imgur.com/TTChrI0

**Comment by Kitzunu** [comment]
>In 4.2, its attunement process was removed and it no longer requires you to run a prior CoT instance.

https://www.wowhead.com/the-black-morass

Fixed, pls test it

**Comment by Kitzunu** [comment]
confirmed by eirolla
