### ISSUE TITLE
[RAID] Bastion of Twilight, Halfus Wyrmbreaker Fight: Proto-Behemoth Fireball

### ISSUE THREAD

**Issue by Eirolla** [WoWManiaUK/Blackwing-Lair#3105]
**Links:**

https://www.wowhead.com/npc=44687/proto-behemoth
https://www.wowhead.com/spell=86058
https://www.wowhead.com/npc=44797/time-warden

**What is happening:**

Need to be tested. 

**What should happen:**

This ability only active while Time Warden is Unchained.

Explaining: Awaken state is 3/5 activated dragons every week.
Explaining: Slumber state is 2/5 of deactivated dragons every week.

**Comment by bagi84** [comment]
during the Halus wyrmbreaker fight the summons 3 out of 5 drakes in normal and actives all 5 during hc when the time warden is dormant(not active in fight because the weekly drakes in normal are diffrent ones) the proto behemoth can only use fireball when he is active it buffs the Proto behemoth with fireball barrage increasing there speed untill you kill him(free him) and he cast time dilation slowing the fireballs and making them easier to dodge

**Comment by Echinaceax** [comment]
team is retesting
