### ISSUE TITLE
[General] Energy Problems with vehicles. 

### ISSUE THREAD

**Issue by Bloodborne93** [WoWManiaUK/Blackwing-Lair#3238]
[NPC/Raid] Salvaged Chopper From Ulduar.

**Links:**
https://www.wowhead.com/npc=33062/salvaged-chopper
from WoWHead 

**What is happening:**
Getting inside the Chopper i got no energy and it got no regen.
![Salvagedchopper](https://user-images.githubusercontent.com/52720024/64491916-f7aba400-d26d-11e9-82f2-88ad899e6821.jpg)

**What should happen:**
It's must have 100 energy and regen it always you use an ability.

**Comment by Rushor** [comment]
will combine those 2 https://github.com/WoWManiaUK/Blackwing-Lair/issues/3423

**Comment by Rushor** [comment]
[Raid] Eye of Eternity 

Links:
https://www.wowhead.com/the-eye-of-eternity
What is happening:
The problem is in last phase when you need to defeat (https://www.wowhead.com/npc=28859/malygos) while you are on a dragon. The problem is you start with 0 energy and you cannot attack him at all https://imgur.com/OLoEn25 --- https://www.wowhead.com/npc=30161/wyrmrest-skytalon
What should happen:
Dragons should start with 100 energy then regenerating it after using skills

**Comment by Rushor** [comment]
[Quest]Aces High! - Borean Tundra

[Aces High!](https://cata-twinhead.twinstar.cz/?quest=13413) is a quest in [Borean Tundra](https://cata-twinhead.twinstar.cz/?zone=3537) , [Coldarra](https://cata-twinhead.twinstar.cz/?npc=32548) high above [The Nexus](https://cata-twinhead.twinstar.cz/?area=4120) [Corastrasza](https://cata-twinhead.twinstar.cz/?npc=32548) is the quest giver no problem so far however I have to kill 5 [Scalesworn Elite](https://cata-twinhead.twinstar.cz/?npc=32534) I have to speak to [Corastrasza](https://cata-twinhead.twinstar.cz/?npc=32548) to summon a drake called [Wyrmrest Skytalon](https://cata-twinhead.twinstar.cz/?npc=32535) to use it for kills which has no energy at all to use any of his abilities , I had to body pull 5 [Scalesworn Elite](https://cata-twinhead.twinstar.cz/?npc=32534) and kill them with my class abilities in order to complete it the [daily version](https://cata-twinhead.twinstar.cz/?quest=13414) comes upon complete the quest and the same issue occurs.
![wowscrnshot_011619_144306](https://user-images.githubusercontent.com/33905184/51249792-14246480-199d-11e9-943e-c6f268c5f657.jpg)

**Comment by Rushor** [comment]
fixed !

![I](https://i.imgur.com/GRqUMJn.jpg)
