### ISSUE TITLE
[Item] Leaden Despair - Trinket

### ISSUE THREAD

**Issue by Venom64bit** [WoWManiaUK/Blackwing-Lair#3390]
**Links:**
https://www.wowhead.com/item=56347/leaden-despair&bonus=4155
**What is happening:**
Doesn't respect the proc conditions.
It is always activated.

**What should happen:**
It must respect the proc conditions:
"Melee attacks which reduce you below 35% health cause you to gain 2580 bonus armor for 10 sec. Cannot occur more then once every 30 sec."

**Comment by Rushor** [comment]
okay try now pls, should have 30 seconds cooldown now.

**Comment by dagget1337** [comment]
The trinkets Armor doesnt apply either, upon wearing it it doesnt give the 1285 armor which it should. maybe since the stat is kinda an enchant, thing, since its written in green it doesnt act like a stable stat? Dunno how to explain, but maybe the same applies to every item too with such ´greened` stats.

**Comment by Echinaceax** [comment]
@Rushor can you check again please
