### ISSUE TITLE
[spell/priest] Inner Will

### ISSUE THREAD

**Issue by Steffiden** [WoWManiaUK/Blackwing-Lair#3451]
**Links:**

https://wow.gamepedia.com/Inner_Will

**What is happening:**

Mana cost of instant cast spells is reduced by 16.67%. I calculated it with multiple different spells. Example in images: ((5250-6300)/6300) * 100% = -16.67%

**What should happen:**

Mana cost of instant cast spells should be reduced by 15%.

![With Inner Will](https://user-images.githubusercontent.com/55976671/65863254-146c6080-e370-11e9-82ad-7099280fed17.PNG)
![Without Inner Will](https://user-images.githubusercontent.com/55976671/65863256-146c6080-e370-11e9-936b-7ee14e11d575.PNG)

**Comment by Keader** [comment]
Has a visual bug in mana used.
BaseMana of lvl 85 priest is 20590
Power word shield uses 34% of base mana, so 20590 * 0.34 = 7000.6 (core truncate the 0.6, so stay with 7000)
7000 - 15% = 5250, value showed after inner will.
So... the problem here is visual, caused by wrong tooltip value (or maybe wrong priest base mana?)
But... talent is working correctly.
