### ISSUE TITLE
Fire mage - Cauterize spellID 86949 

### ISSUE THREAD

**Issue by Zul7030** [WoWManiaUK/Blackwing-Lair#3492]
**What is happening: When taking Fatal damage and the HP is more than 40%, ......let's say the HP is 80%..... , Cauterize will be activated and the HP will remain 80%, this happens only when the HP is more 40% but when it less, the spell works fine**

**it does not matter how much HP the mage has, the HP should be always 40% as the talent says:**

![Cauterize](https://user-images.githubusercontent.com/53161918/66076240-68dd2f00-e56e-11e9-92e4-cf676c557c85.png)

**Comment by Randomplayerx** [comment]
I did not understand what you wrote, XD
but the talent basically works like Protection Paladin ability.

An attack that suppost to kill you, Lets imagine you have 10200 hp and you recieve an attack that suppost to kill you, an attack that deals 10500(300 damage overkill), instead of killing you, it brings you to 40% of your total HP than it start to ticks.

we can clearly see that on fight like Ultraxion Heroic.

**Comment by APTX4869s** [comment]
"Lets imagine you have 10200 hp and you recieve an attack that suppost to kill you, an attack that deals 10500(300 damage overkill), instead of killing you, it brings you to 40% of your total HP than it start to ticks."
what is happening here, if your hp is 10200 and the attack did 10500 your hp will stay 10200 and it will increase on it 40%  of your max hp
tested it in Grim batol second boss with 2hand ( Mace ) 
my hp was around 50-60%, got 1 hit for like 140k damage ( more than my max hp ) which it should activate the 40% but what happened what my hp went to nearly full and started to burn the 40%.

**Comment by Randomplayerx** [comment]
So that's is incorrect indeed.

The Cauterize is healing effect [Green heal]
It should heal you to 40% of your hp, and also Cauterize is affected by healing reduction effect such as Mortal Strike and healing absorbers like Necrotic Strike

**Comment by APTX4869s** [comment]
same goes to retribution's talent " Sacred Shield " sometimes it activates even if your hp was 50% or more ( still don't know why )
I think it's also linked to this problem, I'll try to figure it out and going to open a report about it if needed.
