### ISSUE TITLE
Fire mage - Ignite stacking ( Ignite spellID 12846 

### ISSUE THREAD

**Issue by Zul7030** [WoWManiaUK/Blackwing-Lair#3493]
the source : https://wowwiki.fandom.com/wiki/Ignite_(old)

there is an issue with how does ignite stack, unfortunately I couldn’t know what it is.
So, I would like to explain how it does stack 
As known, Ignite damage divided into 2 portions, it deals damage at 2 sec remaining and 0 sec remaining.
The stacking can happen before the first portion ( 2 sec remaining ) and after it.

Before the first tick : the 2nd crit , it stacks with the previous one by 100% of its damage
After the first tick :  half of the current ignite will be added to the next crit

I have made these tables below, and I hope it will help to understand how does it stack, especially after the first tick

this is an example, getting several crits in a row, just to give an idea how does it stack

this is before the first tick 
https://www4.0zz0.com/2019/10/02/22/369263187.png

this is after the first tick
https://www4.0zz0.com/2019/10/02/22/508782034.png

**Comment by Randomplayerx** [comment]
Ignite is tricky, and that's not so correct that if you crit above 2 seconds it's gives 100% stacking.
You can clearly see that on Alysrazor fight when Mage fight with 25+1 stacks and Pyroblast is like 0.8 sec cast-time, it's not stack to inifnite.

**Comment by Zul7030** [comment]
True , because you need to wait like 0.8-0.9 sec to hit crit to avoid ignite getting munched,  I think I have mentioned that before, anyways, this is how should ignite stacks, it does not matter if it munched or not,
 and there's a cap for ignite you may check my previous report for it

**Comment by Zul7030** [comment]
Above 2 seconds …...it does not provide the whole ignite damage but it does stack ,, half it is lost, you may wanna see the source that I placed

**Comment by Randomplayerx** [comment]
I can't view your previous reports, But I can guess what it talks about.

Reaching more than 150k~ ignite would be a mircale, specially when 400 Ilvl & more Mages are doing like 35-65k [or More] Ignite in Twinstar, that possible when boss is taking extra damage like Deathwing in Cataclysm buff which increase the damage taken. but, anyway reaching 65k has very low chance, many of them clicking Combustion much earlier.

The Ignite cap to 300k like what Atlantiss.eu had was total wrong because their Ignite stacking mechanic was wrong aswell.

So tbh, I don't understand of what 'ignite cap' you talk about there no-mage that will reach more than 100k anyway.

**Comment by Zul7030** [comment]
it's true that getting high ignite is something … miracle as you said, and yea … the cap .... tbh I couldn't a number that written says that this is ignite cap... make it infinite or there is a cap won't make a difference 

35-65 k .. is this combustion damage or ignite ? per tick or whole? if this is combustion( 35k) damage , you need to get ignite around 60k( per tick) which equals around 4-6  crits and It depends on how much you hit and ..yea should be before the first tick which it something .. miracle

**Comment by Randomplayerx** [comment]
Dude, I won't talk about the Cap anymore, the cap is not what should bother, they can cap it to 300k or 500k or leave it inifnite, nobody will reach it anyway. 

when we talk about Ignite we talk about Ignite PER TICK like what addons such as CombustionHelper show you. Please, stop trying to confuse me.

I wrote it pretty good although my English is lame.
good Mages with proper gear 400Ilvl DS gear, most of them doing like 35-45k Ignite which considers pretty good to click Combustion.

And believe me they do crit 4-5 times in a row, and yes it depends on how much damage you hit. If I wrote 400+ Ilvl it means they hit pretty hard, yet 35-45k Ignite.

https://www.youtube.com/watch?v=9DXdGN43jE4

**Comment by Zul7030** [comment]
this is a video from retail ... not private server
https://www.youtube.com/watch?v=OOo-9p_-AXc

see how ignite is increasing,  reached 350k ( yes I know that has the buff), comparing to the video that you brought the mage as well had the same buff but the stacks stopped at 40k maybe , 
well mate ... I think retail wins mate

if ignite stacking is  not as I wrote , according to what you say this?
it you don't have a solid proof, kindly let the dev do their work

1 more things .. the numbers in the tables are just examples, in game you can't keep hitting like the number that I put, it just to make easy to explain it

**Comment by Randomplayerx** [comment]
I saw those videos many times. I also read about how Ignite should work in retail from Blizzard forums
https://us.battle.net/forums/en/wow/topic/4038617617 like here.
like here
https://github.com/Atlantiss/BugTracker/issues/5539

like this pic
https://www.google.co.il/imgres?imgurl=http%3A%2F%2Fi.imgur.com%2F838LR.gif&imgrefurl=https%3A%2F%2Fgithub.com%2FAtlantiss%2FBugTracker%2Fissues%2F5539&docid=xM-qZbgZJy_wnM&tbnid=unOG8Qq_aLBfjM%3A&vet=10ahUKEwj-jv69wf7kAhVKaVAKHcNhDS8QMwhQKBcwFw..i&w=1025&h=781&itg=1&safe=active&bih=694&biw=1517&q=ignite%204.3.4&ved=0ahUKEwj-jv69wf7kAhVKaVAKHcNhDS8QMwhQKBcwFw&iact=mrc&uact=8

I'm just saying that what you talking right now, our "discussion". is exactly the same as other already did on other Pserver, their ignite on Alysrazor like you saw on the video is like 48k highest ticking.

https://cata-twinhead.twinstar.cz/?issue=7813&highlight=ignite#comments

and they did few reworks on their Ignite, as I said I can't provide information about how Ignite exactly works. If this server want to make it broken like it was on Atlantiss.eu good luck with that.

**Comment by APTX4869s** [comment]
your link actually matches what @Zul7030  said
![Zul said](https://user-images.githubusercontent.com/55243287/66084481-cded5080-e57f-11e9-9a1a-d2aa82bddf46.png)

**Comment by Randomplayerx** [comment]
@APTX4869s Yeah everything is said I already knew.
The problem is the ignite in private server cannot be full re-produced back than in 2015 I spoke in private with Shadowlolz the Dev of Twinstar.

There things with spell-delay and registering-auras server refresh is like between 0.2-0.5sec.
Some of the information that provided like by Elitejerks and Blizzard forums are incorrect.

There thing that called "Free tick" that private servers cannot byproduct because of spell-delay.

button line we know how Ignite mechanic works, and the most accurate one is like in Twinstar
in the video I provided, the highest ignite tick on Alysrazor was 48k

Here the video: https://www.youtube.com/watch?v=9DXdGN43jE4

**Comment by Rushor** [comment]
Guys. We want simple demands what we have to fix. Easy advice. Fast fix. Thanks.

**Comment by Zul7030** [comment]
@Randomplayerx 
mate idk why you said twinstar's ignite is the most accurate.  if blizzard ( those who made the game)
made ignite stacking as the explaination above,
in addition you linked a source that MATCHES with what I explained,
To sum it up, I believe this wow reign is a blizzlike, not twinstar-like so it should work as much as possible as blizzard

these are the sources that provided by both of us and has the same explanation
https://wowwiki.fandom.com/wiki/Ignite_(old)
https://user-images.githubusercontent.com/55243287/66084481-cded5080-e57f-11e9-9a1a-d2aa82bddf46.png

I think both of us should leave the dev team to decide what to do with Ignite

**Comment by Randomplayerx** [comment]
@zul7030 i know the numbers was just an example dont make me fool. I know also time traveling matter till the fire/pyro actually hits the target.

What I said was clearly accurate. Anyway I deleted my messages. GL

**Comment by Randomplayerx** [comment]
well, Twinstar are Blizzlike aswell. don't try to reduce their success in making their server good, as I said their this server hasn't smarter or better players or devs than what they have there, if they done their Ignite that way It means something. Again I deleted my message and this message will be deleted in few hours.

We know how Ignite is suppost to work, I wrote down what are the problems to produce it.
I really wish good luck to Reign wow devs to do so, yet as I wrote in the message I deleted, I'm afraid they will make the ignite broken, the only way to fix Ignite as It should be is by analysing World of Logs from 4.3.4 patch.

Ignite is very tricky because there alot of shit to include like "Ignite bank", letancy, travel time, munching, server sides, refresh time, and more shit we wrote down.

I post those links to show off, that I know what you talking about, yet I think there missing information ;), again good luck.

**Comment by APTX4869s** [comment]
@Randomplayerx
1- " as I said their Reign-wow hasn't smarter or better players or devs than what they have there, " on which logic you said that? 
2- there are many servers don't follow twinstar's ignite is that mean they are all wrong? one of them you mentioned it many times before. in case if you don't know what you said " Atlantiss "
3- all you say is " We know how Ignite is suppost to work, " but did you even explain it by yourself? nah.
4- I took this picture from one of your links before you delete all your comments and it's from Twinstar. ( I don't understand his explains because it's not in English )
![7 secs](https://user-images.githubusercontent.com/55243287/66238151-f30ccb00-e707-11e9-9bdc-405417c31093.png)
ignite in around 7 secs got to 51k with alys buff and that buff actually stays more than 7 secs
you don't think in full duration you can actually get more than 51k ignite? ( as I said it's from twinstar ) as I remember you said 44k ignite but in this picture in 7 secs it got to 51k ?????
5- I asked you before about his second part of the report and you still didn't reply if that how it should work or not, you kept talking about the first part of the report, that means to me you don't have enough knowledge about the class too.
6-You edited every single of your comments more than 7 times to each comment and changing the whole comment over and over and over that means to me you aren't sure of what you are saying
7- Deleting your comments won't solve anything .... I don't understand the logic behind it.
8- Why you still didn't bring any sources about your OWN reports? such as https://github.com/WoWManiaUK/Blackwing-Lair/issues/3462 and don't forget, it should be from retail.

**Comment by Keader** [comment]
I will look it tomorrow.
Already has enoght information :)
