### ISSUE TITLE
[NPC] Darkmoon Faire Mystic Mage (Thunder Bluff)

### ISSUE THREAD

**Issue by realdude19** [WoWManiaUK/Blackwing-Lair#358]
### When you accept the quest "[The Darkmoon Faire] ID 7926" 

**You normally can speak to the mage to get ported to the Faire for a fee, but at this time you unable to do so. The Mage doesn't have the option to get the Portal/teleport.**

![2019-01-04 02_15_47-world of warcraft](https://user-images.githubusercontent.com/46016748/50683502-1cf15f80-0fc7-11e9-876c-752cce9a5644.png)

See Quest: https://www.wowhead.com/quest=7905/the-darkmoon-faire

As a summary : 
1. you have to be level 6 or higher and not yet done this quest.
2. you get this quest from the Darkmoon Faire Mystic Mage in the major cities (see below for the Horde cities).
3. the Darkmoon Faire Mystic Mage can transport you to the staging ground for DMF (for a price dependent on level).

**Comment by Dranah** [comment]
May be related to https://github.com/WoWManiaUK/Blackwing-Lair/issues/124
Whole DMF is pretty lacking as it appears atm.

**Comment by Rushor** [comment]
teleport added. 

![I](https://i.imgur.com/HIl6M4l.jpg)

everything else needs new individual report

**Comment by Sammy974** [comment]
The issue about that mage is more complicated. 
When the DF is running, the Mystic mage appear in every capital city:

> Alliance locations
> Darnassus: next to the portal to Rut'theran Village
> Exodar: outside the Bank
> Ironforge: outside the Auction House
> Stormwind City: outside the Auction House in the Trade District
> Horde locations
> Orgrimmar: next to the Flight Master
> Silvermoon City: at the entrance of the city
> Thunder Bluff: at the base of the central totem tower
> Undercity: in the Trade Quarter
> Neutral locations
> Dalaran: in the middle of Runeweaver Square
> Shattrath: outside the Auction House

Last week, according to the calendar, DF should be running but there wasn't any Mystic Mage in Orgrimmar and any portal in Thunder Bluff. NB: The Mystic mage is supposed to teleport you to the portal outside Thunder Bluff, NOT to the DF island.

The Thunder Bluff Mystic Mage is there all the time and if DF is not running and there's no portal in TB... where is he supposed to teleport you? xD

So... 
1) TB Mystic Mage have to be fixed because he appears when the DF is not running, not just because he gives not teleport.
2) The timing of the DF have to be fixed accordingly to the calendar. All the Mystic Mages have to spawn only during that week and give the chance to teleport to the portal located outside TB.

**Comment by Echinaceax** [comment]
Apparently still has issues 
GM told me @Rushor

**Comment by Echinaceax** [comment]
saw this was newest #2700
