### ISSUE TITLE
Druid  spell Swiftmend

### ISSUE THREAD

**Issue by adel4241** [WoWManiaUK/Blackwing-Lair#3593]
https://classic.wowhead.com/spell=18562/swiftmend

**What is happening:** healing too much then usual with out any item healing 20k and with gear even 80k healing ...

**What should happen:**normal heal i test it in two other server and both was like that , with out any gear i saw only 8k healing

**Comment by Sammy974** [comment]
I'm not sure this spell is bugged, the output seems right to me. Anyways "i tested it in other servers" is not a good point, we need to check the blizzard one because the "other servers" could be customized or bugged as well. Pls get some sure info about the spell before to touch it, i will help if i can.

**Comment by Keader** [comment]
Yeah was wrong.
Was using Wotlk behavior + Cataclysm behavior, making spell OP '-'
Fixed.
