### ISSUE TITLE
[General] Flight Path - Issues.

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#3660]
**Links:**

[Flight Path] The Exodar - Tower of Estulan Feralas
from WoWHead or our Armory

**What is happening:**
https://imgur.com/a/xgiWGEP
Took the flight from Exodar to Tower of Estulan in ferals and this happend.
https://imgur.com/a/UOFx3qo

**What should happen:**
When you take a Flightpath you should not get sent into the water. 
It should be a smooth flight without getting stuck on the mount.

**Comment by Rushor** [comment]
Same problem as described before but on a different path. I believe it may occur at every path that includes Ghostlands but i didn't check it. Check the links below for screenshots.

https://gyazo.com/a2b67facdb94829db25f4639f2787022

https://gyazo.com/5e5b28aad110c20ebf5464779a9c7f54

**Comment by Rushor** [comment]
https://www.wowhead.com/npc=39898/shyn

![fp feralas](https://user-images.githubusercontent.com/39439201/50734841-829b4280-11a5-11e9-8d5f-97e5119a1036.jpg)

The npc isn't inactive, the flight path appears to be. So she doesn't have anything to say until you have connecting flight paths, normally she should say "You don't have any flight paths connected to this one".
You can use her to fly elsewhere, but from other FPs, you cannot see this one as an option.

**more info**

- Exactly 

cant see this flight from other Feralas PF either 

![fp fer](https://user-images.githubusercontent.com/39439201/50739057-be043400-11da-11e9-9b22-92011735f9c2.jpg)

- And None of the 3 FPs in Feralas are showing from ORG
- Only 1 from Desolace
- IMO the breakage is because of the FP in desolage i reported here #391

![des](https://user-images.githubusercontent.com/39439201/50739553-78e40000-11e2-11e9-85d0-a60d34b69d1b.jpg)

**Comment by Jimpaa** [comment]
@Rushor I did a few test and this is what i could find as alliance. (See Picture)
Seems like its only on the deadzone that you get dismounted.
So as alliance you always fly through the deadzone if u fly from Exodar - Darnassus/Kalimdor
Bloodmyst isle - Darnassus/Kalimdor. 

Not sure if it helps but i did try and i found a deadzone where u always get dismounted. 

https://imgur.com/a/fwIqyhg

**Comment by sarahkay88** [comment]
@Rushor r I reported something similar a while back but it could not be reproduced at the time #362

**Comment by Rushor** [comment]
thanks for the info, but i think only keader is able ti fix that

**Comment by Jimpaa** [comment]
Tested Exodar - Darnassus on dev. No issues
