### ISSUE TITLE
Raid ID Reset seems daylie now ?

### ISSUE THREAD

**Issue by Slydee23** [WoWManiaUK/Blackwing-Lair#3674]
**Links:**

![Screenshot_3](https://user-images.githubusercontent.com/55513205/67157663-7b59b580-f32f-11e9-9970-740a7254261b.jpg)

from WoWHead or our Armory

**What is happening:**

i cleared BoT Normal on 19.10 with my Hunter and today my ID is expired and i can clear the Raid again

**What should happen:**

I should only be able to clear the raid once and it should reset every Wednesday

**Comment by Rushor** [comment]
I have nothing todo with that

**Comment by Echinaceax** [comment]
ive informed Janitor, hes on it

**Comment by Rushor** [comment]
maybe just a config issue. the reset command has nothing todo with that :o

**Comment by Slydee23** [comment]
today my hunter did not reset so just from wednes to thursday

**Comment by Slydee23** [comment]
ill close it for now and let you know if it happens again

**Comment by Slydee23** [comment]
ok i know now that the Raid ID for Bastion of Twilight always Resets Sunday 5 a.m. ST. i did raid un Saturday with my Hunter and next day ID was gone after testing yesteday i got id again and it still epxpires sunday

**Comment by Rushor** [comment]
can you check that @Keader pls? :)

**Comment by Keader** [comment]
I have 2 theorys:

1 - GMs reseting a lot of times.

2 - A little bug caused by reset command.

I noticed that reset command has 1 little bug (not fixable).
When GMs reset cooldown using the command, player will still have the old cooldown until he relog (because core load the clean cooldown on player login).
So... may is possible a GM reset, a player do a raid and after relog cd is clean (because his "old cooldown is reseted already by GM command")

but in any case, is not something fixable atm, since i cant find the cause of original issue (that GM command try fix).
We need reproduce case, without it, i cant do nothing.

**Comment by Slydee23** [comment]
I can say for sure it is not the first. The Command resets all ID´s for every player but  i only get the resets on chars where i raid before sunday cause the regular reset is sunday you can reproduce that esay just go raid and check your ID expire Date. and Zinius just used the command twice and it worked well every tiem now with VP and the char where i only raid sundays (cause mainraid).
