### ISSUE TITLE
[Quest] Ashes to Ashes ID 27199 / 27086 - Missing prerequisites too

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#369]
Quest - https://www.wowhead.com/quest=27199/ashes-to-ashes
NPC - https://www.wowhead.com/npc=44453 
required NPC to kill -https://www.wowhead.com/npc=44449/deathguard-war-captain
Unable to locate the required NPC to kill in order to complete the quest. search the area twice.

**Comment by Dranah** [comment]
Confirmed, NPCs are missing, for both factions.
Also, this quest is missing prerequisite on both factions.
https://www.wowhead.com/quest=27197/the-battle-resumes Ally
https://www.wowhead.com/quest=27083/the-battle-resumes Horde

Should unlock
https://www.wowhead.com/quest=27199/ashes-to-ashes Ally
https://www.wowhead.com/quest=27086/ashes-to-ashes Horde

Quest givers: 
https://www.wowhead.com/npc=44453/thassarian Ally
https://www.wowhead.com/npc=44452/koltira-deathweaver Horde

**Comment by Echinaceax** [comment]
- Not both, Horde can give back the the-battle-resumes 
- And pick up ashes-to-ashes
https://www.wowhead.com/quest=27086/ashes-to-ashes.

- found issues with it though

**Found another problem** (horde)

- After giving back the "battle resumes"  (completed)
- The next quest for horde is "supporting the troops"
https://www.wowhead.com/quest=27085/supporting-the-troops

**Objective**
- "slay the human soldiers that are fighting with our deathguards."

- Well the issue is that they are inactive mobs. 
- They are just standing there they are not fighting
- Ive killed a few (no kills added) Just to test
- Quest is not completable 

![defender kills](https://user-images.githubusercontent.com/39439201/50722716-78107880-10d3-11e9-8cf2-a6bcdd4373ec.jpg)
![no kills added](https://user-images.githubusercontent.com/39439201/50722722-89598500-10d3-11e9-82cd-54e93c547bb7.jpg)

- Should i make a separate report for this ?

**Comment by sarahkay88** [comment]
the https://www.wowhead.com/quest=27197/the-battle-resumes pre quest wasn't missing I could pick it up after doing the quest in this area and then riding to the flight path made it available. I remember because when I picked it up I had to go back and I hated the area haha

**Comment by Dranah** [comment]
Missing prerequisite means that the quest should require another quest to be completed before it is available.

**Comment by Rushor** [comment]
okay questcondition and creatures added.
