### ISSUE TITLE
[Spell] Death Knight (Frost) - Frost Fever(DoT)

### ISSUE THREAD

**Issue by Batraneluu** [WoWManiaUK/Blackwing-Lair#3777]
**Links:** 

from WoWHead or our Armory
https://www.wowhead.com/spell=55095/frost-fever#see-also-ability
**What is happening:**
Doing very low damage (link: https://imgur.com/a/JmDNSgw )
829damage/second
**What should happen:**
If that link is correct the damage of the spell should be like this:
20/100 x 7100 = 1420
now if we add the talent Virulance wich increases the diseases damage by 30% will be:
30/100 x 1420 = 426
and if we add mastery wich is 33% now on my character (link: https://imgur.com/a/9ijhHD4 ) damage should be:
33/100 x 1846 = 609
and the total damage will be 1420 + 426 + 609 = 2455 / second

**Comment by Keader** [comment]
That link is wrong (is from BFA)
In cataclysm is: ```${$m1*1.15+$AP*0.055*1.15} ``` where $m1 is effect0 value, that is ```0 + Level * 0.32```

i checked my self, and this part is totally working.

Checking more stuffs:

That formula above, give me 333 in frost fever.

333 * 1.27 (My DK Mastery) = 422.91
422.91 * 1.3 (Virulence) = 549.78

My game result:

![image](https://user-images.githubusercontent.com/7120913/68027744-ed1bf280-fc91-11e9-907a-7130d19e3264.png)

The little difference (about 1~2) is caused by truncation errors (422.91 for core is 422, he ignore the 0.91)
