### ISSUE TITLE
[Quest] The Battle Resumes! - Missing prerequisite - Western Plaguelands

### ISSUE THREAD

**Issue by Dranah** [WoWManiaUK/Blackwing-Lair#379]
https://www.wowhead.com/quest=27197/the-battle-resumes Ally
https://www.wowhead.com/quest=27083/the-battle-resumes Horde

These quests should only be unlocked once you handed it Combat Training.

Missing prerequisites: https://www.wowhead.com/quest=27174/combat-training Ally
https://www.wowhead.com/quest=26938/combat-training Horde

Quest chains unlock in wrong order which can cause phasing and other issues.

**Comment by Echinaceax** [comment]
**Found another problem** (horde)

- After giving back the "battle resumes"  (completed)
- The next quest for horde is "supporting the troops"
https://www.wowhead.com/quest=27085/supporting-the-troops

**Objective**
- "slay the human soldiers that are fighting with our deathguards."

- Well the issue is that they are inactive mobs. 
- They are just standing there they are not fighting
- Ive killed a few (no kills added) Just to test
- Quest is not completable 

![defender kills](https://user-images.githubusercontent.com/39439201/50722716-78107880-10d3-11e9-8cf2-a6bcdd4373ec.jpg)
![no kills added](https://user-images.githubusercontent.com/39439201/50722722-89598500-10d3-11e9-82cd-54e93c547bb7.jpg)

- Should i make a separate report for this ?
