### ISSUE TITLE
The Call of The World-Shaman Quest line Bugged

### ISSUE THREAD

**Issue by tonigalo** [WoWManiaUK/Blackwing-Lair#3877]
**https://www.wowhead.com/quest=29440/the-call-of-the-world-shaman
https://www.wowhead.com/quest=29335/into-slashing-winds**

from WoWHead or our Armory

**The initial quest: The Call of the World Shaman doesn't have the cinematic nor does starting the quest with Thrall initiate the chain correctly. You can auto-complete the first quest at Aggra but she then doesn't teleport you nor does Thrall vanish. When manually flying to Uldum in order to find Cyclonian for "Into Slashing Winds" the NPC isn't there hence the whole chain is bugged**

**After initiating the first quest Thrall should disappear as he is divided into four elements and Aggra should teleport the player into Uldum to meet Cyclonian, repeating this process into 3 more zones (Deepholm, Vashjr and Firelands) every time you finish the challenge**

**Comment by Priestelar** [comment]
This quest line should NOT be available yet since it was only made available in patch 4.2 and we are still in patch 4.1. 
This quest line sends you into the Molten Front which is also only added in 4.2 just to give you an idea of it.
![image](https://user-images.githubusercontent.com/16594771/68582970-b8bfe780-0484-11ea-9855-d93886cc6967.png)

**Comment by Rushor** [comment]
will disable it

**Comment by Rushor** [comment]
quests removed from the queststarters for now.
