### ISSUE TITLE
[Quest] Opening the Door Quest not working

### ISSUE THREAD

**Issue by tonigalo** [WoWManiaUK/Blackwing-Lair#3883]
**https://www.wowhead.com/quest=29145/opening-the-door*

from WoWHead or our Armory

**The NPC where i need to turn in the quest isn't where he's supposed to be. Arch Druid Hamuul Runetotem is still at the sanctuary of malorne instead at Nordune Ridge.**

**A new phase should be started with Hamuul Runetotem and other NPCs gathering infront of the flame portal at Nordune Ridge.**

**Comment by Priestelar** [comment]
Should not be working atm as the intire Molten Front quest line was only added in patch 4.2 and we are still in patch 4.1 atm.
![image](https://user-images.githubusercontent.com/16594771/68681508-327ed080-056c-11ea-8435-5bd892f445d3.png)
Plus untill hyjal is fixed this quest line cannot be done since you need to complete the hyjal quest lines in order to reach this mentioned quest.

**Comment by Echinaceax** [comment]
we are actually 4.0.3  so even more so 
@rushor what you think?

**Comment by Rushor** [comment]
lets remove the line for now

**Comment by Rushor** [comment]
removed for now.

DELETE FROM `gameobject_queststarter` WHERE `quest` IN (29390, 29391, 29387, 29388, 29389);
DELETE FROM `creature_queststarter` WHERE `quest` IN (29390, 29391, 29387, 29388, 29389);
