### ISSUE TITLE
"Dungeon Finder" The Eye for que

### ISSUE THREAD

**Issue by Jimpaa** [WoWManiaUK/Blackwing-Lair#4010]
**Links:**

from WoWHead or our Armory

**What is happening:**

When i use a portal or just travling around the world and get a cutscene it kicks me from the dungeonfinder. If im in grp with someone and that person que us up the eye will vanish but we will still be in que.

**What should happen:**
The eye should not vanish or kick you out of dungeon finder when you use a portal or get a cutscene out in the world.

**Comment by sarahkay88** [comment]
I can confirm that part of this is ac visual bug, my group the other day all used the portol to deepholem. We were queed for rdf. After portol none of us had the green eye. Because we were rare hunting we decided not to requeue. However around 5/10 minutes later the queue popped and we ended up in a rhc.

**Comment by sarahkay88** [comment]
However if solo queued it requires a fresh queue

**Comment by Rushor** [comment]
movd to https://github.com/WoWManiaUK/Blackwing-Lair/issues/4011
