### ISSUE TITLE
[Quest][NPC] Dar'Khan's Lieutenants (9170) - Masophet the Black Missing

### ISSUE THREAD

**Issue by Vortexsphere** [WoWManiaUK/Blackwing-Lair#4015]
**Links:**

Quest: https://www.wowhead.com/quest=9170/darkhans-lieutenants
Missing NPC: https://www.wowhead.com/npc=16249/masophet-the-black

**What is happening:**

The NPC, Masophet the Black, is not spawning in any of the locations he's meant to. All of the other NPCs for the quest work and respawn in the correct locations like they should, but this one is missing (the entire area was checked thoroughly and no one else was there so I know I didn't randomly miss it).

**What should happen:**

Masophet the Black should spawn in one of various locations in southern Deatholme. All private servers I've played on had him spawn in a static location in the southeastern ziggurat, but wowhead shows a few others too.

**Comment by Rushor** [comment]
either here https://i.imgur.com/hhrtP7k.jpg or there https://i.imgur.com/LOKEO6G.jpg

**Comment by Echinaceax** [comment]
this was fixed before here #767
something must have gone wrong

**Comment by Velara** [comment]
I noticed that issue when I did a search and I assume the reporter had no issues with this NPC at the time. Perhaps it was broken with a fix since then or perhaps it just never occurred then. I did notice there was a rare mob in the ziggurat where Maphoset is supposed to be, that I've only ever seen on the ziggurats near the Dead Scar where you loot orbs for a different quest (the exact name escapes me, it was some undead doctor mob I think). Maybe that is related? In any case, Rushor says he's fixed it now so all good I hope.

**Comment by Echinaceax** [comment]
yes could have been @Velara

**Comment by Echinaceax** [comment]
Reopening this issue, Notified from GM this is still and issue

**Comment by Echinaceax** [comment]
Dupilcate 
will fix this one https://github.com/WoWManiaUK/Blackwing-Lair/issues/1657
