### ISSUE TITLE
Rigid Cogwheel and Precise Cogwheel Missing from Engineering Vendor.

### ISSUE THREAD

**Issue by Mellowish4767** [WoWManiaUK/Blackwing-Lair#4113]
https://wowwiki.fandom.com/wiki/Cogwheel  - ForReference since WoWhead links got updated

item id -59493 - Rigid Cogwheel
https://wowwiki.fandom.com/wiki/Rigid_Cogwheel
item id -59489 - Precise Cogwheel
https://wowwiki.fandom.com/wiki/Precise_Cogwheel

These 2 are missing from vendor.

These should be avaiable for purchase

**Comment by Echinaceax** [comment]
### Confirmed both ally and horde are missing 
Precise Cogwheel http://cata.cavernoftime.com/item=59489
Rigid Cogwheel http://cata.cavernoftime.com/item=59493


Billibub Cogspinner http://cata.cavernoftime.com/npc=5519 
Frank Natale http://cata.cavernoftime.com/npc=49702
Gearcutter Cogspinner http://cata.cavernoftime.com/npc=5175

also horde
Sovik http://cata.cavernoftime.com/npc=3413
Vizna Bangwrench http://cata.cavernoftime.com/npc=45546
Zim Bamzabble http://cata.cavernoftime.com/npc=50460

thanks @Mellowish4767

**Comment by Rushor** [comment]
okay that addition is now done for Lure Master Tackle Box and Elementium Toolbox.
Remember: Both required item must be EMPTY in inventory or bag slot, them the trade item will be shown. Else the core will delete the item if items are contained in Lure Master Tackle Box and Elementium Toolbox. The was a big issue because of taht back in the days, so i added that condition.

![I](https://i.imgur.com/s0IdLGh.jpg)
![I](https://i.imgur.com/uwUWjj8.jpg)
