### ISSUE TITLE
[NPC] Marin Noggenfogger (7564) missing - Tanaris 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4142]
**Links:**

npc https://classic.wowhead.com/npc=7564/marin-noggenfogger
quests https://classic.wowhead.com/npc=7564/marin-noggenfogger#starts

![7564 missing](https://user-images.githubusercontent.com/39439201/71673254-9eb1cf80-2d78-11ea-91d7-7b25d8eaf3c6.jpg)

**What is happening:**
- NPC missing (7564)

**What should happen:**
_should be here to give quests, especially the one for the Elixir_ 
https://classic.wowhead.com/item=8529/noggenfogger-elixir

**Comment by Rushor** [comment]
he was removed https://www.wowhead.com/npc=7564/marin-noggenfogger#comments

Chief Engineer Bilgewhizzle is the previous leader of Gadgetzan. Somehow Marin Noggenfogger managed to usurp him. Given the vast fortune Marin accumulated from Noggenfogger sales to adventurers I can only imagine he had sufficient gold to 'buy his way in'.

Oh yeah. Since the Shattering, Marin also seems to have a wife: Sprinkle Noggenfogger.

So what happened to Bilgewhizzle during the Cataclysm? We might never know, sadly.

C'mon Blizzard, give us a fun (neutral) goblin quest chain to fill out the lore!
Last edited by Taraezor on 2018/03/10 (Patch 7.3.5)

but to by the item the condition was removed aswell. will remove that.

you can by the item from spinkle now https://i.imgur.com/s4HdEUi.jpg
