### ISSUE TITLE
[Quest] Runaway Shredder! qid 14129 Azshara

### ISSUE THREAD

**Issue by Chargelol** [WoWManiaUK/Blackwing-Lair#4153]
**Links:**
quest 
https://www.wowhead.com/quest=14129/runaway-shredder
npc
https://www.wowhead.com/npc=35086/labor-captain-grabbit

**What is happening:**
labor captain grabbit doesnt offer this quest .

**What should happen:**
shoud offer this quest lookup starts quest from npc link ;) .
also this quest starts a series.

1.Report to the Labor Captain (goblin quest)

1b.Warchief's Command: Azshara!

2.Runaway Shredder!
3.The Captain's Logs
4.Up a Tree
5.Defend the Gates!
6.Arborcide

migth be missing cause Report to the Labor CaptainWarchief's Command: Azshara! is also missing.

**Comment by Kadajj** [comment]
Only gives Report to Horzak (ID: 14162) quest.  See in Chatbox the 2 quest completed.

![WoWScrnShot_041120_193419](https://user-images.githubusercontent.com/38867875/79052024-83821600-7c2b-11ea-8d49-f71689b20d4b.jpg)

**Comment by Echinaceax** [comment]
Updated

ive edited reporter 1st post 

1.Report to the Labor Captain (goblin quest)

and if player takes **Warchief's Command: Azshara!** then yes Runaway Shredder! is offered

**Comment by mfranca0009** [comment]
This needs re-testing, because at the moment what is being said is the complete opposite of what is happening on the database side. @Echinaceax 

Quest 28496 (https://www.wowhead.com/quest=28496/warchiefs-command-azshara) Has a previous Quest requirement for it to be unlocked and it has a Quest that will be awarded when it is turned in.

The prerequisite that is required is this quest in order to open up the Azshara's warchief command quest: https://www.wowhead.com/quest=25267/message-for-saurfang

Once that quest is completed, Warchiefs command azshara quest will be available (also if the player is the proper level of course). Once the Warchiefs command azshara quest is turned in, the database has set 14129 (https://www.wowhead.com/quest=14129/runaway-shredder) as the next quest in the chain to be given.

Need a re-confirmation on this to know if this is still a problem or not, right now, the quest chain looks intact and is giving out the proper quests at the proper time.

**Comment by Echinaceax** [comment]
@mfranca0009 
from what i can see the only race that gets this quest https://www.wowhead.com/quest=25267/message-for-saurfang  
is a goblin (as i stated above) 

![goblin](https://user-images.githubusercontent.com/39439201/106158329-e7a6a400-6183-11eb-9e77-b28357d92b4e.jpg)

when other races follow the questline is starts with https://wow.gamepedia.com/Azshara_storyline

![image](https://user-images.githubusercontent.com/39439201/106159642-4fa9ba00-6185-11eb-8377-4ebb40fbe466.png)

also see that the Beyond Durotar quest closes the **Report to the Labor Captain** and **Warchief's Command: Azshara!**
![closes](https://user-images.githubusercontent.com/39439201/106160530-381f0100-6186-11eb-9ff6-3aada0053b92.jpg)

**Comment by Echinaceax** [comment]
### update

Once i added the Warchief's Command: Azshara! #5040 and delivered it to npc
i was given the quest 
![image](https://user-images.githubusercontent.com/39439201/106274981-6dcef300-6235-11eb-8ea9-f2526013fea6.png)

quest completed too, BUT with another issue #5041

![image](https://user-images.githubusercontent.com/39439201/106275193-bd152380-6235-11eb-848b-fa3308e9c218.png)

quest delivery via your questlog 

![image](https://user-images.githubusercontent.com/39439201/106275306-e33ac380-6235-11eb-878d-a7ba890ae927.png)


Captains log offered now 

![image](https://user-images.githubusercontent.com/39439201/106275414-11200800-6236-11eb-95c1-85b4945a72e2.png)

**Comment by Echinaceax** [comment]
### Fully tested 

Findings are as follows:

1. once #5040 is fixed then your other quests are given via the questlog not the npc 
2. once #5045 is fixed then i can test the actual quests 

closing this atm coz the quests are not actually missing, the **Warchief's Command: Azshara!** missing is the main issue here for the quest oder at least
