### ISSUE TITLE
[Quest] Like Rats - ID 27620 - Eastern Plaguelands

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#417]
Quest - https://www.wowhead.com/quest=27620/like-rats
NPC - https://www.wowhead.com/npc=16116
Unable to complete this quest due to the NPC - https://www.wowhead.com/npc=46096 Crusader Lord Valdemar missing.
![world of warcraft 07_01_2019 14_01_50](https://user-images.githubusercontent.com/42302580/50772434-b2ba1280-1285-11e9-9671-e9c7820efc61.png)

**Comment by sarahkay88** [comment]
has a side not I wanted to add that this is the last quest in a series of 8 but I only received the last 3 of them. 
the following quest were missing:
https://www.wowhead.com/quest=27612
https://www.wowhead.com/quest=27613
https://www.wowhead.com/quest=27615
https://www.wowhead.com/quest=27619
please let me know if you require a separate report for each quest missing.

**Comment by Dranah** [comment]
This need to be looked into. According to wowhead:
"In order to unlock "Victory from Within" you must first complete:

The Brotherhood of Light
Soft Landing
To Take the Abbey

The quest "To Take the Barracks" is required to unlock:
Scarlet Salvage
The Wrathcaster
The Huntsman
The Commander"

I can see "Victory from Within" and "The Assassin" available without any prereq completed, however i can only take one of them, each closes the other. This is absolutely not intended.

**Comment by Echinaceax** [comment]
Horde has some issure with this series of quests too
- The Brotherhood of Light (completed)
- To Take the Abbey (completed)
- "Victory from Within"  cant complete as the video shows 
Video - https://www.wowhead.com/quest=27612/victory-from-within#videos:id=66827

**Comment by Echinaceax** [comment]
Horde has issues with this too 
https://www.wowhead.com/quest=27620/like-rats

- The Brotherhood of Light (completed)
- To Take the Abbey (completed)
- cant complete "victory-from-within" cant complete as show in the video

Quest - https://www.wowhead.com/quest=27612/victory-from-within
Video - https://www.wowhead.com/quest=27612/victory-from-within#videos:id=66827

**Comment by Rushor** [comment]
spawnpoint adde for the creature.
