### ISSUE TITLE
Phasing problem / Group / Raid issue

### ISSUE THREAD

**Issue by Chicozoba** [WoWManiaUK/Blackwing-Lair#4192]
What is happening: A bug that occured a few months ago and that has been fixed is back apparently. Huge lags happen when several members of a group are in different locations.

What should happen: Game should be smooth I guess ^^

I tried to disable all my addons, the problem is still here. And it happens to a few other people on the server too.

**Comment by Echinaceax** [comment]
It wasnt actually fixed yet https://github.com/WoWManiaUK/Blackwing-Lair/issues/1616 Chicozoba 

> it happens to a few other people on the server too.

I can confirm its HUGE lag
Happens when gathering members from different zones, while we are waiting for summon   
(10 man raid group) 

it has to get some sort of fix i totally agree

@wow-mania https://github.com/WoWManiaUK/Blackwing-Lair/issues/1616#issuecomment-493673304 only thing i can suggest is that you come group with us and we can show you , see from your own experience

players are getting frustrated, we cant afford to lose players over this, we have started rebuilding player base and raid groups are making this issue worse

**Comment by Echinaceax** [comment]
this is what we mean by different phase @Rushor  @wow-mania  @Keader 

![diff phase](https://user-images.githubusercontent.com/39439201/77247224-3ebc1e00-6c2f-11ea-910c-083457e4a1fd.jpg)

please can someone figure this out, it is annoying that we cant group as the game intended.

Raiders/players have to make there own way to raids/World bosses to stop this happening and inv to group when they all get there.

**Comment by Echinaceax** [comment]
### More info from yesterday 
As soon as the "out of phase" icon shows, you start to get the fps issue, look at the distance between **Me** and **Gamer100** Yesterday, this is rediculious. This shouldnt be like this. Surely we have provided enough evidence for you now. 

![distance lag](https://user-images.githubusercontent.com/39439201/77303159-bef78780-6cf2-11ea-9ce5-95c73adb6b70.jpg)

**reproduce**   

1. Make a group 2 3 4 people 
2. Move away from each other (run away oppersite directions)
3. Wait until you see the "different phase" icon
4. then you will lag, stutter, game fps (what ever you get you will notice) 

**I AM WAITING TO TEST THIS IN PVP** lol god help us all

Tested in pvp - no issue :)

**Comment by Keader** [comment]
test if fixed

**Comment by Echinaceax** [comment]
Will test and let you know @Keader :)

**Comment by Echinaceax** [comment]
### Update 
Fix confirmed on dev 
tested with 3 tester in different zones NO LAG

Tester 1 was in ICC 
Tester 2 was in twilight (me) 
Tester 3 was in Vash'ir 

Tester 3 noticed that the phasing icon for Tester 2 wasnt there anymore :)
So Cata zones **phasing icon** is fixed if that is what it was about or not. but no lag was seen at all
in a group of 3

![no phasing  icon](https://user-images.githubusercontent.com/39439201/81946030-264cfc00-95ff-11ea-9b03-ac1ebd543f29.jpg)

### note

But the phase Icon still there when Tester 1 was in ICC  and Tester 2 was in Dalaran

hope this helps @Keader
