### ISSUE TITLE
[Talent] Judgement of the Just - Protection Paladin Spell ID: 53696

### ISSUE THREAD

**Issue by Hespericless** [WoWManiaUK/Blackwing-Lair#4238]
**Links:**
http://cata.cavernoftime.com/spell=53696
http://cata.cavernoftime.com/spell=68055
http://cata.cavernoftime.com/spell=41467

**What is happening:**
The attack speed slow is not applying when you use Judgement with offensive seals (Seal of Righteousness and Seal of Truth), instead it only applies on Seal of Justice and Seal of Insight.

**What should happen:**
As the talent doesn't state a condition for Judgement to proc the attack speed slow, the spell should apply the slow regardless of the seal you're using.

**Comment by Hespericless** [comment]
This was mentioned already in https://github.com/WoWManiaUK/Blackwing-Lair/issues/2682 but, as seen on Keader's screenshot, he's using Seal of Justice, which does apply the attack speed slow. The problem happens when you're with any of the offensive seals.

**Comment by mfranca0009** [comment]
https://wowwiki-archive.fandom.com/wiki/Judgements_of_the_Just

![image](https://user-images.githubusercontent.com/26092980/107883113-ed59f480-6eba-11eb-8ed2-9118b8fa1210.png)


Based on evidence from a WoW source, it only shows information on Seal of Justice and how it effects the duration of the debuff on the target. Provide SOLID evidence that EVERY seal should proc this debuff and we will change it. At the moment, no information points to EVERY seal procing this debuff.

**Comment by Hespericless** [comment]
You know Seal of Justice is there because the talent increases its slow duration, right? The one not providing "SOLID evidence" here is you. Besides, even if your claim is correct, there should still be a fix preventing the talent to proc from Seal of Insight.
I don't play on this server anymore because this is the quality of fixes players are getting.
Please consider reopening this issue, and improving on your reading comprehension. By the way, this talent attack speed slow behaves the same way as it does on WotlK, you could try taking a look at your own server to see how it behaves there :)
K, thx bye

**Comment by Echinaceax** [comment]
no need to be rude @Hespericless

**Comment by mfranca0009** [comment]
For one, I have no access to the WoW-Mania server; only Reign. Two, WotLK is not the same as Cata and therefore will not be considered the same.

I'm not the evidence fetcher, I fix the issues when they're relevant to be fixed with sufficient evidence behind them. If you want to make a report with only spell IDs and no evidence from lets say a Blizzard GM comment, WoW patch note, or anything SUBSTANTIAL to claim the spell isn't working as intended then the issue gets closed; simple as that.

Considering you give me information of what you "assume" because a tooltip doesn't specify if it procs from every seal isn't valid evidence. @Hespericless
