### ISSUE TITLE
[Quest] The Ancient leaf (Ticket 771)

### ISSUE THREAD

**Issue by Adelrico** [WoWManiaUK/Blackwing-Lair#4324]
**Links:**
https://classic.wowhead.com/item=18703/ancient-petrified-leaf
https://classic.wowhead.com/quest=7632/the-ancient-leaf
from WoWHead or our Armory

**What is happening:**
When I right-click the ancient petrified-leaf item in my bags, nothing happens.

**What should happen:**
A quest window should appear giving me the quest: The ancient leaf.

**Comment by Demoniakk** [comment]
That quest was marked Obsolete in Cataclysm and should not even be existing anymore in this expansion. You getting the item is a mistake in enemy loot tables and quests.

**Comment by Echinaceax** [comment]
@Demoniakk can you please link the patch note of this removal please ?

**Comment by Demoniakk** [comment]
https://wowwiki.fandom.com/wiki/Quest:A_Proper_String
seriously ?...

**Comment by Echinaceax** [comment]
https://wowwiki.fandom.com/wiki/Quest:The_Ancient_Leaf is what is reported 

Ofc the report needs links to show the "removed" or now longer ingame, info @Demoniakk

**Comment by Demoniakk** [comment]
https://wow.gamepedia.com/Ancient_Petrified_Leaf
removed after the Shattering.
Quest linked before is the reason it was removed, because in 3.3.5 patch the Mature Black Dragon Sinew drop was changed from Onyxia, which had a loot table changed to lvl 80 stuff, to Burning Steppes black dragons, which every one of them had a chance to drop the item. In patch 4.0.1 it also changed and dragons no longer dropped the Mature Black Dragon Sinew, resulting the removal of Ancient Petrified Leaf and it's quest, The Ancient Leaf, from game as a whole in 4.0.3, being marked as obsolete.

**Comment by Echinaceax** [comment]
Thank you for info @Demoniakk very helpful.

With this being a "progressive" server we have to get the info given correct, I hope you understand

As for https://wow.gamepedia.com/Lightning-Charged_Battlegear this needs a seperate report

**Comment by mfranca0009** [comment]
Item dropped from:
https://classic.wowhead.com/npc=11663/flamewaker-healer
https://classic.wowhead.com/npc=11664/flamewaker-elite

Quest does not exist in-game. This should be fixed now; needs testing in PTR 👍
