### ISSUE TITLE
[Rogue][Talent] Overkill buff timer not reseting correctly

### ISSUE THREAD

**Issue by Calmwindx** [WoWManiaUK/Blackwing-Lair#4513]
**Links:**
https://cata.cavernoftime.com/spell=58427

from WoWHead or our Armory

**What is happening:**
The rogue talent Overkill is not working correctly. Whenever you exit stealth you should get a 20 second timer on Overkill. However, if you exit stealth, then re-enter it and exit again before the first 20 second timer is up, the buff is not refreshed and will expire after the first 20 second timer.

**What should happen:**
Entering stealth normally, or by Vanish should reset the timer on overkill.

**Is it crashing the server?:**
Nope.

**Other Information:**
If you stay in stealth longer than the first 20 second timer, the overkill buff does reset, it just wont reset the timer till the first is finished.

**Comment by mfranca0009** [comment]
I confirmed this, it was counting the original 20 second timer and removing the buff after 10 seconds of leaving stealth the second time.

**Now with fix:**

- [x] Timer executed on leaving Stealth
- [x] If going back into stealth, the original timer will be removed.
- [x] Leaving stealth again, you'll have a fresh timer of 20 seconds when overkill will be removed.

I tested this fix with Vanish as well, and since vanish transitions you into normal stealth, it seems to work fine as well now 👍

**Comment by golosomie** [comment]
@mfranca0009 Confirmed fixed on PTR. Working with normal stealth and Vanish as expected.

**Comment by Yamios** [comment]
Now there is another bug in overkill if you leave stealth and respec to subtlety before the buff expire . OverKill buff stay in subtlety and never expire .

**Comment by mfranca0009** [comment]
@Yamios This is a different problem than the original issue. Please open a new issue and report it.
