### ISSUE TITLE
[Quest] Eyes Of Desire - Sethekk Halls

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4576]
**Links:**

quest http://cata.cavernoftime.com/quest=29607
quest item drop http://cata.cavernoftime.com/item=72480

**What is happening:**
- no Cobalt Eye dropping 

**What should happen:**
Cobalt Eye quest item should drop from http://cata.cavernoftime.com/?search=Cobalt+Serpent
https://www.youtube.com/watch?v=JleSRmbaqjQthe cobalt surpent

**Comment by mfranca0009** [comment]
Cobalt Serpent NPC needs their whole loot table corrected, they should drop 466 items and only has 15 rows in loot table now.

http://cata.cavernoftime.com/npc=19428

Will start working on this.

**Comment by mfranca0009** [comment]
Weirdly enough, but the percentage for most of the loot has a 0% drop chance or at least it shows that. I'm assuming it has a lower drop chance than 0.1 and then it stops displaying the drop chance percentage on Cavern of Time....

I used WoWhead for drop percentage chance for Cobalt Eye because it wasn't listed on Cavern of Time for some reason.

Will mark as fixed for now, since the original issue has been fixed; needs testing in PTR 👍

**Comment by Echinaceax** [comment]
confirmed fixed in PTR

![fixed33](https://user-images.githubusercontent.com/39439201/89511647-7ee0ff00-d7d2-11ea-820f-6911a6bafad2.jpg)
