### ISSUE TITLE
[Talent/Warlock] Molten Core

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#463]
Searches
 https://www.wowhead.com/search?q=molten+core+warlock+talent
https://www.wowhead.com/spell=159609/molten-core

- Cant find the talent reference on wowhead
- I never use immolate, but Molten core still proccs
- Odd that demonology can take 3/3 talent when 1 of the spells it boosts is not available until lvl 64.

immolate  Spell https://www.wowhead.com/spell=44518/immolate  
Incinerate Spell https://www.wowhead.com/spell=44519/incinerate

![molton core](https://user-images.githubusercontent.com/39439201/51041172-a30a3900-15b9-11e9-9ba2-60b278d11ef3.jpg)

![incinerate](https://user-images.githubusercontent.com/39439201/51041285-dc42a900-15b9-11e9-9441-a6b208e71f22.jpg)

**Comment by Dranah** [comment]
Wowhead is updated to patch 8.0 so it is missing alot of references and links.
Being able to talent something you don't yet have is no news. You can spec Improved Felhunter on wotlk as an affliction long before your felhunter learns their Shadow Bite ability.

The issue here seems to be proc by outer source. Need to identify what else procs it besides Immolate.

**Comment by Keader** [comment]
Fixed.
If i forgot to restart dev, use .reload spell_proc before test.
Will proc only with immolate now.

**Comment by Echinaceax** [comment]
will do Keader thanks :)

**Comment by Kitzunu** [comment]
Only proccs from Immolate now.
However, when you get the Molten Core buff, it has 3 stacks, each stack empowers Incinerate ability.
When you cast Incinerate, the stacks do not get reduced, so basically what happens is that you can have 15seconds of empowered Incinerate instead of 3 casts

**Comment by Keader** [comment]
Fixed.
