### ISSUE TITLE
[Quest] Corrupting Influence? (Ally) - Ashenvale

### ISSUE THREAD

**Issue by mfranca0009** [WoWManiaUK/Blackwing-Lair#4685]
**Links:**

https://www.wowhead.com/quest=13868/corrupting-influence
https://www.wowhead.com/item=46128/troll-charm

**What is happening:**
This item is dropping for horde players, but it leads to an alliance quest

**What should happen:**
Item should not drop for horde players; only alliance.

**Is it crashing the server?:**
No

**Other Information:**
N/A

**Comment by Echinaceax** [comment]
still dropping for my horde hunter @mfranca0009 
![image](https://user-images.githubusercontent.com/39439201/107159293-3bd53380-698f-11eb-9bb3-5b065eb45568.png)

**Comment by mfranca0009** [comment]
item still drops (even when I set the conditions properly), but the player can't accept the quest because it's Alliance only.

Fixed as best as possible.

**Comment by Echinaceax** [comment]
confirmed partly fixed in PTR
still drops for horde but they cant accept the quest.
hordes just throw it away :)

![image](https://user-images.githubusercontent.com/39439201/107160461-9cb43a00-6996-11eb-8897-762e4da74641.png)

Ally can accept with no issue 

![image](https://user-images.githubusercontent.com/39439201/107160768-932bd180-6998-11eb-9ced-71e7d6eaba9b.png)
