### ISSUE TITLE
[NPC] Dame Evniki Kapsalis - Argent Tournament

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4726]
**Links:**

npc https://www.wowhead.com/npc=34885/dame-evniki-kapsalis#comments
Achiv horde https://www.wowhead.com/achievement=2816/exalted-argent-champion-of-the-horde
Achiv Ally https://www.wowhead.com/achievement=2817/exalted-argent-champion-of-the-alliance
title https://www.wowhead.com/title=156/crusader

**What is happening:**
- After getting all requirements for access to the Quartermaster She still cant be viewed 

needed for npc upgrade  https://www.wowhead.com/item=47541/argent-pony-bridle

**What should happen:**
_According to WoWWiki, you must first become an Argent Crusader by earning the achievement Exalted Argent Champion of the Alliance or Exalted Argent Champion of the Horde before you will be permitted to purchase items from this NPC._

**Other Information:**
![have requirement](https://user-images.githubusercontent.com/39439201/92981458-31734400-f49a-11ea-9a96-d28e1ba6a1c6.jpg)

**Comment by mfranca0009** [comment]
Created a C++ script to check if player has proper achievement. If player does not have proper achievement, then it will provide the npc text that the screenshot shows above (Echi's screenshot). If player does have proper achievement, it will open vendor.

NPC also needed editing for it's vendor items, since this vendor should not have heirlooms for purchase until Warlords of Draenor expansion. Wrath of The Lich King version of NPC only sells 5 items (No Heirlooms). I removed the heirlooms and kept the 5 items that should be present. One item is specific to paladins, so it won't show up for all characters.

**Comment by Echinaceax** [comment]
### Horde confirmed fixed in PTR

**Without the requirements (Crusader achv)**

![without crusader achv](https://user-images.githubusercontent.com/39439201/93318739-586da500-f80f-11ea-8566-35930c1768a1.jpg)



**With the rquirements (Crusader achv)**

![horde confirmed2](https://user-images.githubusercontent.com/39439201/93201606-b6d44e00-f751-11ea-8349-f8828be89550.jpg)

Ally 

**With the rquirements (Crusader achv)**

![ally fixed](https://user-images.githubusercontent.com/39439201/93201631-bf2c8900-f751-11ea-9e9c-f178ec1d91b1.jpg)

**Comment by mfranca0009** [comment]
@Echinaceax  As you said, Cavern of Time showed some heirlooms so I have adjusted the NPC vendor to add them back.

It seems there may have been some extra items in there anyways, since there are now 27 slots and originally there were 31. 

Should now be all set completely 👍

**Comment by Echinaceax** [comment]
Ok @mfranca0009 👍
