### ISSUE TITLE
[Dungeon] Sacrifice Timer - Zul'Aman 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4794]
**What is happening:**
- Sacrifice Timer is not adding extra time bonus after killing bosses

**What should happen:**
extra timer should be added after killing each boss 

**Other Information:**
this issue is stoping players from completing the quest https://github.com/WoWManiaUK/Blackwing-Lair/issues/4596

**Comment by mfranca0009** [comment]
Found this link:
https://wow.gamepedia.com/Zul%27Aman_timed_event

it states only Nalorakk gives 15 minutes and Akil'zon gives 10 minutes, but it states that the page subject was removed for patch 4.1.0. 

We need information on how much time is given after a boss is killed; specifically what bosses give time.

**Comment by mfranca0009** [comment]
This video:
https://www.youtube.com/watch?v=b3yeYGEgTgQ

Akil'zon and Nalorakk only give 5 minutes on kill, Jana'lai and Halazzi DOES NOT give time on kill.

This information seems most relevant because the gamepedia link above states that information was deprecated cause of patch 4.1.0. The video here was posted April 30th, 2011, which was 4 days after patch 4.1.0 release.

**Comment by mfranca0009** [comment]
Per the evidence listed above, Akil'zon and Nalorakk now give off 5 minutes each after killed.

Fixed in PTR, needs testing 👍
