### ISSUE TITLE
[Quest] Rescuing the Expedition - The Underbog

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#4836]
**Links:**

from WoWHead or our Armory

**What is happening:**
one mob is dead and i can talk to him the 2nd mob is never to be around

**What should happen:**
the 2nd mob should be in the dungeon
**Is it crashing the server?:**
no
**Other Information:**

**Comment by Echinaceax** [comment]
more info needed @almoghr

quest name ...
npc missing ...

**Comment by almoghr** [comment]
[Rescuing the Expedition] - the missing npc is: 
Earthbinder Rage -  https://www.wowhead.com/npc=17885/earthbinder-rayge

**Comment by Echinaceax** [comment]
Found the issue 

1. NPC is spawned Earthbinder Rage - https://www.wowhead.com/npc=17885/earthbinder-rayge

(not missing)


@mfranca0009 
Main issue is that the Fen Rays sliding on the floor kill him before player can complete the quest 
my video https://gyazo.com/b020f87557c30e8eeb1cfb74aacc4367

made seperate report for the Fen Ray here #4842


**New update** 
its https://www.wowhead.com/npc=17894/windcaller-claw that is missing 
location of Windcaller is here on video https://www.youtube.com/watch?v=8B3clcOPIto

**Comment by Echinaceax** [comment]
@mfranca0009 
Added NPC 

entry 17894
GUID 84

1. Still needs sitting position setting
2. need quest completion setting 

![added npc](https://user-images.githubusercontent.com/39439201/97870572-6b7efa80-1d13-11eb-9897-0789e3b9db15.jpg)
![not complete](https://user-images.githubusercontent.com/39439201/97870550-65891980-1d13-11eb-8d62-fabc111c5b03.jpg)

**Comment by mfranca0009** [comment]
Windcaller claw should not be spawned, once you bring "Claw" down to 0 - 20% health he will turn back into Windcaller Claw and you'll be able to get quest progress for discovering him.

Also, the only other issue I can see happening is that when "Claw" turns into "Windcaller Claw", his name does not change from "Claw" to "Windcaller Claw"... I assume this is because it's being ran through SmartAI and the creature is not being completely changed to Windcaller Claw's entry number; it's only morphing to its display ID.

I did however fix Earthbinder Rage so that he doesn't die by the Fen Rays 👍 

Here's a video from 2014: https://youtu.be/0Ir_omhLtpI?t=162

All set and needs testing in PTR @Echinaceax
