### ISSUE TITLE
[Item] Miniature Voodoo Mask - Zul'Aman 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#4877]
**Links:**

https://cata-twinhead.twinstar.cz/?item=69762

**What is happening:**
- Only 1 gnome is spawned not 3 

**What should happen:**

_Use: Calls forth 3 Voodoo Gnomes to destroy your enemies._

**Comment by mfranca0009** [comment]
This spell needs adjusting:
https://www.wowhead.com/spell=98275/death-by-voodoo-gnome

**Comment by mfranca0009** [comment]
All set, three gnomes spawn 👍 

The only problem that still persists is that each gnome is following the player inside each other because they don't have a different follow angle and distance to the player. 

I found a similar issue that is still open within Trinitycore - https://github.com/TrinityCore/TrinityCore/issues/25063

This is a general problem with all creatures, not specifically related to this spell or item.

**Comment by Echinaceax** [comment]
spawn fixed in dev
just needs seperate pathing yes 

![fix needs pathing](https://user-images.githubusercontent.com/39439201/99739449-1130b880-2acd-11eb-8aa3-f71054981b0d.jpg)
