### ISSUE TITLE
quest - i was a lot of things - shadowmoon valley 

### ISSUE THREAD

**Issue by almoghr** [WoWManiaUK/Blackwing-Lair#4934]
**Links:**

https://www.wowhead.com/quest=10514/i-was-a-lot-of-things
**What is happening:**

i am standing near the tube mouns and cant call the boars - it doenst recognise im standing near it

**What should happen:**
the boar should come and do something with the tuber
**Is it crashing the server?:**
no
**Other Information:**

**Comment by mfranca0009** [comment]
This quest works fine, you need to be standing very close to the Tuber mound almost on top of it. Also, you need to make sure that the Domesticated Felboar is within 5 yards of the Tuber mound or the boar will not come over and dig it up. If you watch the video below, you'll notice even this player/youtuber has trouble with some of the Tuber mounds because the Domesticated Felboars are NOT within 5 yards, therefore nothing will happen when you use the whistle.

https://www.youtube.com/watch?v=uIlgWOV-_oQ

![image](https://user-images.githubusercontent.com/26092980/102019227-3cab6980-3d40-11eb-878f-64760d999f46.png)


![image](https://user-images.githubusercontent.com/26092980/102019221-34ebc500-3d40-11eb-8621-8a9d0c9db6bd.png)
