### ISSUE TITLE
jewelcrafting trinkets

### ISSUE THREAD

**Issue by granplanta** [WoWManiaUK/Blackwing-Lair#4943]
**Links:**

from WoWHead or our Armory
 [Figurine - Demon Panther]
**What is happening:**
It droped on a mage without jewelcrafting.

**What should happen:**
Not drop.
**Is it crashing the server?:**
no
**Other Information:**

**Comment by Echinaceax** [comment]
http://cata.cavernoftime.com/item=52199
I seen this drop on my Shammy too dropped from https://www.wowhead.com/quest=28500/the-cypher-of-keset

Same npc @granplanta ?

**Comment by mfranca0009** [comment]
Question on this, 

Do all of the Figurine related items need the player to have a specific jewelcrafting skill level for it to drop? If so, I'll need a full list of figurine related items.

**Comment by Echinaceax** [comment]
these @mfranca0009 
all drops are just for JC

quest drop https://www.wowhead.com/quest=28775/broken-serpent-figurine
reward https://www.wowhead.com/item=52353/figurine-jeweled-serpent

quest drop https://www.wowhead.com/quest=28778/broken-boar-figurine
reward https://www.wowhead.com/item=52351/figurine-king-of-boars

quest drop https://www.wowhead.com/quest=28776/broken-earthen-figurine
reward https://www.wowhead.com/item=52352/figurine-earthen-guardian

quest drop https://www.wowhead.com/quest=28777/broken-owl-figurine
reward https://www.wowhead.com/item=52354/figurine-dream-owl

quest drop https://www.wowhead.com/quest=25047/broken-panther-figurine
reward https://www.wowhead.com/quest=25047/broken-panther-figurine

**Requirements**

End - Automatic
Level 50 (Requires skill 475)
Category - Jewelcrafting
To equip - 85
tricket - Item level is 346

**Comment by mfranca0009** [comment]
Well those are quests, do the quests need fixing too or are you just posting them because the items are attached? @Echinaceax 

Also, there are quest starting items and equip-able  figurines, are they both dropping without any jewelcrafting requirement check or just the equip-able items?

**Comment by Echinaceax** [comment]
the items are attatched to them after they complete the quests
So they should only drop the drop quest for JC professions only 

note: that the start quests cant be used atm, it just asks "you must be a jewelcrafter blah bla" 

![demon panther](https://user-images.githubusercontent.com/39439201/102385049-a8eecd00-3fcd-11eb-88c0-f4ab29eaad0c.jpg)


https://wow.gamepedia.com/Broken_Serpent_Figurine

**Comment by mfranca0009** [comment]
Those are not all of the jewelcrafting figurines that are available, here's the full list right here including equips and items that start a quest:

https://www.wowhead.com/items/name:Figurine+-?filter=99;11;0

Truesilver Crab - https://www.wowhead.com/item=21760/figurine-truesilver-crab
Truesilver Boar - https://www.wowhead.com/item=21763/figurine-truesilver-boar
Emerald Owl - https://www.wowhead.com/item=21777/figurine-emerald-owl
Twilight Serpent - https://www.wowhead.com/item=42395/figurine-twilight-serpent
Jeweled Serpent - https://www.wowhead.com/item=52353/figurine-jeweled-serpent
Jade Owl - https://www.wowhead.com/item=21748/figurine-jade-owl
Crimson Serpent - https://www.wowhead.com/item=35700/figurine-crimson-serpent
Living Ruby Serpent - https://www.wowhead.com/item=24126/figurine-living-ruby-serpent
Dawnstone Crab - https://www.wowhead.com/item=24125/figurine-dawnstone-crab
Dream Owl - https://www.wowhead.com/item=52354/figurine-dream-owl
Dark Iron Scorpid - https://www.wowhead.com/item=21789/figurine-dark-iron-scorpid
Earthen Guardian - https://www.wowhead.com/item=65897/figurine-earthen-guardian
King of Boars - https://www.wowhead.com/item=65895/figurine-king-of-boars
Earthen Guardian - https://www.wowhead.com/item=52352/figurine-earthen-guardian
Dream Owl - https://www.wowhead.com/item=65894/figurine-dream-owl
Seaspray Albatross - https://www.wowhead.com/item=35703/figurine-seaspray-albatross
Talasite Owl - https://www.wowhead.com/item=24127/figurine-talasite-owl
Jeweled Serpent - https://www.wowhead.com/item=65896/figurine-jeweled-serpent
Ruby Serpent - https://www.wowhead.com/item=21769/figurine-ruby-serpent
Black Diamond Crab - https://www.wowhead.com/item=21784/figurine-black-diamond-crab
Sapphire Owl - https://www.wowhead.com/item=42413/figurine-sapphire-owl
Monarch Crab - https://www.wowhead.com/item=44063/figurine-monarch-crab
Nightseye Panther - https://www.wowhead.com/item=24128/figurine-nightseye-panther
King of Boars - https://www.wowhead.com/item=52351/figurine-king-of-boars
Demon Panther - https://www.wowhead.com/item=52199/figurine-demon-panther
Empyrean Tortoise - https://www.wowhead.com/item=35693/figurine-empyrean-tortoise
Felsteel Boar - https://www.wowhead.com/item=24124/figurine-felsteel-boar
Emerald Boar - https://www.wowhead.com/item=42418/figurine-emerald-boar
Black Pearl Panther - https://www.wowhead.com/item=21758/figurine-black-pearl-panther
Demon Panther - https://www.wowhead.com/item=52197/figurine-demon-panther
Ruby Hare - https://www.wowhead.com/item=42341/figurine-ruby-hare
Khorium Boar - https://www.wowhead.com/item=35694/figurine-khorium-boar
Golden Hare - https://www.wowhead.com/item=21756/figurine-golden-hare
Shadowsong Panther - https://www.wowhead.com/item=35702/figurine-shadowsong-panther

I'm assuming from what you're saying, all of these need to have requirement of the player having JC in order for them to drop. I don't see the logic of only some of them requiring JC to drop since all of them require JC to equip or use.

**Comment by mfranca0009** [comment]
This should be all set, needs testing in PTR 👍  @Echinaceax
