### ISSUE TITLE
[Raid] ICC Achievements 

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5013]
### on live we did ICC 10 tonight and we got both 10 and 25 man Achievements 

**Links:**

https://www.wowhead.com/achievement=4604/storming-the-citadel-25-player
https://www.wowhead.com/achievement=4605/the-plagueworks-25-player
https://www.wowhead.com/achievement=4606/the-crimson-hall-25-player
https://www.wowhead.com/achievement=4607/the-frostwing-halls-25-player

**What is happening:**
- giving 10 and 25 Achievements

**What should happen:**
_on 10 man mode we should only get 10 man Achievements_ 

Note: we will make tickets to GM to remove the ICC 25 Achievement

**Comment by mfranca0009** [comment]
### Main Issue

10 man normal raid is sharing progress with 25 man normal raid, and vice versa. The only difference is if you kill `Deathbringer Saurfang` in 25 man normal raid then you won't get the achievement because it doesn't count him as achievement credit; which is a problem.

If you kill `Deathbringer Saurfang` in 10 man normal raid, then you will obtain credit for both the 10 man and 25 man achievement (Storming the Citadel).

In the 10 and 25 man heroic raid, you gain achievement progress for the proper achievement based on the raid difficulty (this is correct behavior). The problem with this, is that `Deathbringer Saurfang` does not give achievement credit when killed; similar to the problem in 25 man normal raid.

**Comment by Echinaceax** [comment]
Note:
that Me and Mfranca have only worked on the https://www.wowhead.com/achievement=4604/storming-the-citadel-25-player for now, So not all have been looked into yet.

Janitor is aware ...

**Comment by mfranca0009** [comment]
Can take a look again later, but at this point it seems like a larger problem is happening and its not differentiating between difficulty for 10 man or 25 man for normal mode.

**Comment by mfranca0009** [comment]
Recently tested, The Frozen Throne achievement (25-man) is also given out in 10-man normal difficulty.
https://www.wowhead.com/achievement=4597/the-frozen-throne-25-player

I haven't tested this, but I assume that Fall of the Lich King (25-man) achievement would also be given out in 10-man normal difficulty as well...

https://www.wowhead.com/achievement=4608/fall-of-the-lich-king-25-player

**Comment by mfranca0009** [comment]
I figured out the problem I was having originally, Storming The Citadel should be fixed for 10man, 25man, 10 heroic, 25 heroic.
Fixing the rest now 👍 

![image](https://user-images.githubusercontent.com/26092980/104795843-598fee00-577f-11eb-9983-501329100aff.png)

**Comment by mfranca0009** [comment]
**All fixed for the achievements listed below that were known to have issues:**
- Storming The Citadel
- The Plagueworks
- The Crimson Hall
- The Frostwing Halls
- The Frozen Throne

If there are any others that are a problem, open new issue.

**Comment by Echinaceax** [comment]
CONFIRMED fixed in PTR
