### ISSUE TITLE
Worgen Female Texture Issue? Also, Not Showing Gear.

### ISSUE THREAD

**Issue by onetoejoe** [WoWManiaUK/Blackwing-Lair#5017]
**Links:**
![20210101_210233](https://user-images.githubusercontent.com/77313605/104268319-dd309e80-5450-11eb-8bfd-2e26c350c8bc.jpg)
![20210101_210521](https://user-images.githubusercontent.com/77313605/104268323-e0c42580-5450-11eb-933d-f1843e53c36d.jpg)

**What is happening:**

My friends and i made worgen characters to level together, 1 was female. After we got bitten in the questline and actually changed into worgen, the female character's body textures were replaced with male, and the face and hair textures were replaced with male face textures....Also, the armor did not show, so she always looked like how she does in the picture, even after changing armor, and trying to relog. 

**What should happen:**
The models should be replaced with the proper ones, so that the female worgen doesnt look like a monster. (and shows your gear)
**Is it crashing the server?:**
No, the game did not crash. No, the server did not crash.
**Other Information:**
I have not tried to replicate the problem. And my friend has not logged back in since then to test to see if the problem is gone. Further investigation would be needed to fiix.

**Comment by Echinaceax** [comment]
@onetoejoe 
there has be a lot of different test and fixes about this issue, from pot transformation use, and form change (two forms) 
i think it was and (running wild) it is a client issue

keader commented here https://github.com/WoWManiaUK/Blackwing-Lair/issues/3021 and fix here https://github.com/WoWManiaUK/Blackwing-Lair/issues/3033

Are you using the newest client 1.1.0 from the Reign site?

hasnt been any new  reports about these for a while, so thought the issue was gone tbh

**Comment by Echinaceax** [comment]
moved to main report #4396
