### ISSUE TITLE
[Spell/talent] Improved Judgement

### ISSUE THREAD

**Issue by Marvin5678** [WoWManiaUK/Blackwing-Lair#5024]
**Links:**

from WoWHead or our Armory

**What is happening:**
Hi in my specs i set Improved Judgement and it must increase distannce but in my case on first target its ok but when i selected on another it isn't. i must cone to target to work sory for my english not my native.
is anyone else experience that

**What should happen:**

**Is it crashing the server?:**

**Other Information:**

**Comment by Echinaceax** [comment]
https://cata-twinhead.twinstar.cz/?spell=87175

**Comment by Marvin5678** [comment]
ohh ok tnx

**Comment by mfranca0009** [comment]
The problem is, https://cata-twinhead.twinstar.cz/?spell=87175, is not actually adding another 20 yards.

First rank, https://cata-twinhead.twinstar.cz/?spell=87174, adds 10 yards (20 yards total)
Second rank, https://cata-twinhead.twinstar.cz/?spell=87175, adds 20 yards (30 yards total)

From what I can see, learning rank 1 works and shows 20 yards, but the second rank makes it go back down to 10 yards and not 30 yards.

**Comment by mfranca0009** [comment]
Rank 2 now will provide a 30 yard range total for Judgement, and reflects that in spell tooltip 👍

**Comment by mfranca0009** [comment]
Can't find an issue with this, Improved Judgement Rank 1 provides 10 additional yards (20 yards total), and Improved Judgement Rank 2 provides 20 additional yards (30 yards total). 

Tested this myself, and I can confirm it gives you the proper range no matter the amount of targets you kill with Judgement or any spell; spell tooltip also reflects the updated spell range.
