### ISSUE TITLE
[Quest] Gluttonous Lurkers - Zul'Drak

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#5244]
**Links:**

https://www.wowhead.com/quest=12527/gluttonous-lurkers

**What is happening:**
- rats can be collected while mounted
player gets the "you are mounted warning" but can still loot while mounted

**What should happen:**
- player should get dismounted when clicking the rats 

https://www.wowhead.com/quest=12527/gluttonous-lurkers#videos:id=76245

**Other Information:**
![image](https://user-images.githubusercontent.com/39439201/120530877-430ccb00-c3de-11eb-9ac3-f5ea1fde6bbe.png)

Saw mania report so tested here
confirmed same bug as Mania

**Comment by Lumber-Jack-2** [comment]
Or at least a error Warnung that says you are mitunter. Can give you the fix :)

**Comment by Echinaceax** [comment]
> Or at least a error Warnung that says you are mitunter. Can give you the fix :)

Did you set the dismount player on your fix too @Rushor or just the error message?

**Comment by mfranca0009** [comment]
I wouldn't say we need a warning message, most spells that require you to be dismounted just call the generic dismount spell so the player is automatically dismounted when the spell begins to cast. That would be a better alternative, since then the player doesn't have to keep dismounting manually and can then just click the rat to dismount/cast spell at the same time.

**Comment by Lumber-Jack-2** [comment]
Hm alright, yes that sounds better

**Comment by Echinaceax** [comment]
confirmed fixed in ptr
