### ISSUE TITLE
[Quest] Aiding the Outrunners - missing prerequisite

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Blackwing-Lair#545]
in Sunstrider Isle the starting zone of Blood Elves the NPC named [Lanthan Perilon ](https://www.wowhead.com/npc=15281/lanthan-perilon)should give 3 quests total the first one is [Aggression](https://www.wowhead.com/quest=8334/aggression) and the second is [Aiding the Outrunners](https://www.wowhead.com/quest=8347/aiding-the-outrunners) both work just fine but the third quest that should give named [Felendren the Banished](https://www.wowhead.com/quest=8335/felendren-the-banished) isn't exist.

**Comment by Dranah** [comment]
The quest is there, if you do the chain in the right order. 
This seems to be an issue with Aiding the Outrunners appearing too early.
Quest order should be:
1. Report to Lanthan Perilon
2. Aggression
3. Felendren the Banished
4. Aiding the Outrunners

However if you re lvl 4 or above you can see Aiding the Outrunners available without any prerequisites. Accepting this quest closes the Felendren quest, so that it doesn't show up once you've completed Aggression.
