### ISSUE TITLE
[Npc] Angels summoned by Ancient Guardian dont do nothing

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Blackwing-Lair#563]
Need be scripted

**Comment by Keader** [comment]
Fixed

**Comment by Dranah** [comment]
Guardian now properly heals for holy and defends for prot, however does not properly attack for ret.
He hits for 50-70 on an average low lvl mob which is ridiculous, but the real issue is that he does not auto attack at all for most of the time.
Trying to find a logic behind, i came up with this: the angel only seems to properly melee if you summon him before you attack the enemy. If you summon him while you're punching something, he just won't do shit, no matter if you try to move around, get him closer or anything.

**Comment by Keader** [comment]
Hmm, good catch.
Fixed it too.
but about 50-70 avarage damage, we need find some source about real damage.
I realy dont know how handle it right now.

**Comment by Keader** [comment]
Ok, found evidences for how it scales.
Fixed.

**Comment by Dranah** [comment]
Looks good, both behavior and scaling

**Comment by KrinkHorde** [comment]
Angel should be untargetable(all speecs, at the moment he dies with one shot bcs it's targetable and only got 12k hp even aoe dmg works on him) and be on assist mode when summoned [ retri ] every case i repetance one target and summon angel while hiting 2nd target he goes for the cced one so basicly you can't use cc and use the angel
