### ISSUE TITLE
[Spells] Guardian Fury

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Blackwing-Lair#564]
Spell need do damage to closes targets when Ancient Guardian is removed.

**Comment by Dranah** [comment]
This works now, however as you can't get stacks of Ancient power, I cannot test if the damage scales properly with those. I've added that to the other report.

**Comment by Keader** [comment]
Fixed it too

**Comment by Dranah** [comment]
Works as intended when the effect expires, however does not work properly with the condition when the guardian is killed. "After 30sec or when your guardian is killed..."
Right now if your guardian dies, you continue gaining stacks of Ancient power as long as the duration on the spell holds instead of the stacks blowing up and dissipating. It releases the fury when the duration ends as if your guardian wasn't killed.

**Comment by Keader** [comment]
Fixed.
