### ISSUE TITLE
[bug] water surface and flying mount [low piro]

### ISSUE THREAD

**Issue by Icytalon** [WoWManiaUK/Blackwing-Lair#565]
when I am on the water surface and attempt to fly with my mount i can't nether by summon mount while in water nor getting in water while i was flying before.

**Comment by Dranah** [comment]
I don't fully understand the issue. "On water surface" means while swimming?
Pretty sure you're not meant to be able to mount up while swimming.
Please link some kind of evidence if I am wrong.

As for "getting in water while I was flying before" this has been hotfixed since BC:
_In one of the older patches in The Burning Crusade, flying mounts were adjusted so that you are no longer dismounted when coming into contact with water. That also made it impossible to dive into the water without manually dismounting from your flying mount._

**Comment by Icytalon** [comment]
@Dranah if you are flying and get down into the water you can't fly back again and if you are swimming and summoned a flying mount you can't fly either

**Comment by gantor2** [comment]
i believe this wasnt originally meant to be possible in retail. Yet later on they did make it so you could

**Comment by Dranah** [comment]
Cannot reproduce this issue. 
- Touching water surface with a fly mount works as intended, you aren't able to breach the water surface and you can keep flying. 
- Entering a lake from the ground (using your fly mount as a ground mount) does not dismount you as long as you stay near surface. And from there, you can take off and fly.
- Submerging deep into water with will dismount you and pop a breathe timer.

Cannot find a problem here.
