### ISSUE TITLE
[Quest] Enhancing the stone (Horde) - missing prereq - Blasted lands

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#631]
quest - https://www.wowhead.com/quest=25693/enhancing-the-stone
npc missing - https://www.wowhead.com/npc=7783/loramus-thalipedes

- Cant hand in, NPC isn't there 

Related
#627

**Comment by Dranah** [comment]
The NPC isn't present due to https://github.com/WoWManiaUK/Blackwing-Lair/issues/636

This quest is missing prerequisites, should not be available without completing the prequels, nor it is doable without them (no loramus).

This is the HORDE version https://www.wowhead.com/quest=25693/enhancing-the-stone 
Should require:
https://www.wowhead.com/quest=25689/time-is-short
https://www.wowhead.com/quest=25692/the-vile-blood-of-demons
https://www.wowhead.com/quest=25691/the-charred-granite-of-the-dark-portal

Ally version of the quest chain is slightly different and the quests are not exactly the same.

**Comment by Echinaceax** [comment]
i completed 
https://www.wowhead.com/quest=25692/the-vile-blood-of-demons
https://www.wowhead.com/quest=25691/the-charred-granite-of-the-dark-portal

**Comment by Rushor** [comment]
spawned the creature so far and added the prequests
