### ISSUE TITLE
[Spell] Seal of Justice - ID 20170

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Blackwing-Lair#632]
Is being applied from Hammer of Wrath and Divine Storm, though clearly says Single-Target meele attacks.

Reprod Steps of HoW:  Have the talent of Sanctified Wrath, put SoJ -> Avenging Wrath -> Hammer of Wrath, you'll notice seal applying.

Divine Storm speaks for itself, an AoE attack applying seal to all its targets though it's supposed to be single target only as a limitation.

Divine Storm ID: 53385
Hammer of Wrath ID: 24275

**Comment by Keader** [comment]
Removed proc with Divine Storm.
Like other case, Hammer of Wrath is not considered aoe damage.
Any proof that it should not proc?

**Comment by Dranah** [comment]
DS no longer procs the seal. (fixed)
HoW still does, but that'll receive an own thread because HOW currently procs all seals.
While HoW is indeed not aoe damage, the problem is it's not a melee attack either.
Its a 30yrd range spell, which is categorized as "ranged attack with non physical damage" according to wowwiki which makes it non eligible to proc any seals.
