### ISSUE TITLE
[Spell] Seal of Insight - ID 20165 / 20167

### ISSUE THREAD

**Issue by Ashamedlol** [WoWManiaUK/Blackwing-Lair#644]
Issue 1: Seal procs by using Hammer of Wrath and Divine Storm, though it should be single target meele attacks only.

Issue 2: Seal is not restoring 4% of base mana, rather restores way lower. (just restores 4 mana per hit)

Issue 3: Seal is proccing on every hit, it's supposed to be a chance to proc.

"Fills the Paladin with divine power for 0sec, giving each single-target melee attack a chance to heal the Paladin for x and restore 4% of the paladin's base mana. Only one Seal can be active on the Paladin at any one time."

Hammer of Wrath ID: 24275
Divine Storm ID: 53385

**Comment by Keader** [comment]
But Hammer of Wrath is a Single Target spell.
Fixed for divine storm.
Proc chance in dbc is 100% and wow head say the same... If dbc/wowhead is wrong, how much it need be?
Mana issue fixed.
Just waiting about Proc chance to send... but i realy think that it should 100% like all other seals, they just wrote wrong.
@Ashamedlol , @Dranah

**Comment by Keader** [comment]
Hmm, looks like it's 100% proc chance, but can happens 20 procs per minute. Cool.

**Comment by Keader** [comment]
Fixed.

**Comment by Dranah** [comment]
No longer proc'd by DS (fixed)
HOW should not proc it because HoW is not a melee attack, but I opened a separate thread for that since it's an issue with HoW and all seals.
Mana restore 4% as intended. (fixed)
The remaining issue here is that the proc chance is still 100% with no ppm mechanism or anything. It simply procs off all melee attacks.  (need fix)

**Comment by Dranah** [comment]
Good now.
