### ISSUE TITLE
[Quest] The Amulet of Grol - ID 26169 - Blastedlands.

### ISSUE THREAD

**Issue by sarahkay88** [WoWManiaUK/Blackwing-Lair#655]
Quest - https://www.wowhead.com/quest=26169/the-amulet-of-grol
NPC - https://www.wowhead.com/npc=42298
ITEM: https://www.wowhead.com/item=10753
The item is in the correct place however once looted it doesn't go in your inventory and doesn't complete the quest.
Quest incompletable. 
Has a side note there was lag.. But attempted this 3 times

**Comment by Rushor** [comment]
can be looted form there creatures https://www.wowhead.com/item=10753/amulet-of-grol#dropped-by

**Comment by zippoking** [comment]
Object: https://www.wowhead.com/object=203230/head-of-grol

Thats only partially true. 

How it is:
When you click the head of grol, the mob does not spawn.
![Amulet of grol - how it is](https://user-images.githubusercontent.com/18005338/59130726-86a7d800-8970-11e9-8433-ded3f411bfd4.png)


How it should be:
When you click the head of grol, immediately, an image of Grol will spawn behind you. You must kill him to obtain the real Amulet of Grol, which he drops as loot.
But since he is not spawning, you can´t loot him and finish the quest!
![Amulet of grol - how it should be](https://user-images.githubusercontent.com/18005338/59130968-3bda9000-8971-11e9-9ee6-822883c4f8ad.png)
