### ISSUE TITLE
[NPC] Vim'gol the Vile - 22911- (Missing)  Blade's Edge Mountains

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#742]
NPC - https://www.wowhead.com/npc=22911/vimgol-the-vile

**_Vim'gol must be summoned by standing within a fire ring at his circle. Find Vim'gol's Circle in the mountains_**

- NPC vimgol-the-vile not at location 
- Cant complete 

For the quest
quest - https://www.wowhead.com/quest=10998/grim-oire-business

![fire](https://user-images.githubusercontent.com/39439201/52918550-a3a09880-32f8-11e9-8564-551eb9558d30.jpg)
![not here](https://user-images.githubusercontent.com/39439201/52918552-a69b8900-32f8-11e9-874e-f87aa547cd89.jpg)

**Comment by Dranah** [comment]
The way it's intended to work is that you need to stand in the flame circles on the outer side:
Originally (back on BC) it required a party of 5 to summon him, because you needed 1 in each circle. Now it should require only one, someone standing in whichever circle.
The NPC will then spawn on the rune in the middle.

How it works atm: cannot seem to trigger the spawn with just 1 person. Perhaps the issue is that it still requires 5?

**Comment by Rushor** [comment]
![I](https://i.imgur.com/i1LMtuH.jpg)
