### ISSUE TITLE
[Spells] Some Pet Hunter spells not scaling with hunter status

### ISSUE THREAD

**Issue by Keader** [WoWManiaUK/Blackwing-Lair#750]
Claw(16827), Smack(49966), Bite(17253) is not scaling with hunter attackpower.

**Comment by Dranah** [comment]
Something is off here. I just began testing this numerically and the pets abilities are dealing insane damage, about twice as much as they should.
Example:
Claw 16827 has base points of around 187 and an AP scaling of 0,4x0,2 = 0,08
So it gets 8% of hunter RAP, in theory.
The tooltip and the calculations both say it should deal, for a hunter with 3120 RAP, 187 + 249 damage = 436
The actual damage done is 902
So... it's overscaling somehow. The attack power coefficient calculates to be around 23% instead of 8% atm.

**Comment by Keader** [comment]
Any chance of this can be caused by Wild Hunt @Dranah ?

**Comment by Dranah** [comment]
Nope, I tested without talents.

**Comment by Keader** [comment]
Test now
i found other system conflicting with this.

**Comment by Dranah** [comment]
No change.

**Comment by Dranah** [comment]
Getting closer. Current coeff seems to be around 10% instead of 8 still.

**Comment by Keader** [comment]
I looked to all core, nothing more is added wrong here.
I realy dont will waste more time in this issue...
