### ISSUE TITLE
[Quest item] Wrangling Rope - 32698 - Blade's Edge Mountains

### ISSUE THREAD

**Issue by Echinaceax** [WoWManiaUK/Blackwing-Lair#753]
item - https://www.wowhead.com/item=32698/wrangling-rope

- for the quest - https://www.wowhead.com/quest=11065/wrangle-some-aether-rays
- Item not working when its clicked
- Invalid target error 

![rope](https://user-images.githubusercontent.com/39439201/53204947-34df7a00-362d-11e9-9301-781d2234a63a.jpg)

![invalid target](https://user-images.githubusercontent.com/39439201/53205074-8ab42200-362d-11e9-9975-1e032fd181e4.jpg)

at this point not sure if its a problem with the item or the Aether Ray
https://www.wowhead.com/npc=23343/wrangled-aether-ray

**Comment by Keader** [comment]
Quest itens, is not with me.
Is with Rushor '-'
I can help if is some spell issue, but i'm pretty sure it's condition case xD

**Comment by Dranah** [comment]
"once it is ready to be wrangled" 
he is invalid because he is not ready to be wrangled. you have to weaken the mob first...
Generally these "capture" items work if the mob is below 35%
![WoWScrnShot_051119_071637](https://user-images.githubusercontent.com/31132743/57565353-ca80df00-73bc-11e9-928b-933c473b3dfb.jpg)

**Comment by Echinaceax** [comment]
> Generally these "capture" items work if the mob is below 35%

It apprears i was an other Over geared test toon (my bad)
Update noted
