### ISSUE TITLE
[Quest] Forced to Watch from Afar - ID 313 - Dun Morogh

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#823]
**Links:**
Quest - https://www.wowhead.com/quest=313/forced-to-watch-from-afar
Pick Up Npc - https://www.wowhead.com/npc=40950
Npc Required to Speak to - 
https://www.wowhead.com/npc=40991 - Mountaineer Dunstan
https://www.wowhead.com/npc=40994 - Mountaineer Lewin
https://www.wowhead.com/npc=41056 - Mountaineer Valgrum
from WoWHead or our Armory

**What is happening:**
Once Targeting NPC for Completion no Chat or Script is available on any of the Above NPC required to complete the quest.

**What should happen:**
 You Should be able to Targeting NPC for Speech or Script for Completion of the quest  

![world of warcraft 07_03_2019 22_52_41](https://user-images.githubusercontent.com/45798884/53995042-c4a41e80-412b-11e9-9b1b-75d007784c39.png)

**Comment by bagi84** [comment]
All 3 NPC's Checked and all are same

**Comment by iTz-AddriX** [comment]
**Confirmed** #4312

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/119258257-31027f80-bbc9-11eb-8a2e-9543a34baa90.png)
![image](https://user-images.githubusercontent.com/39439201/119258309-673fff00-bbc9-11eb-9daa-1b49f9cff205.png)
![image](https://user-images.githubusercontent.com/39439201/119258356-8d659f00-bbc9-11eb-9459-73f687f74e17.png)
