### ISSUE TITLE
[Quest] Strike from above -ID 25841 - Dun Morogh

### ISSUE THREAD

**Issue by bagi84** [WoWManiaUK/Blackwing-Lair#827]
**Links:**
Quest - https://www.wowhead.com/quest=25841/strike-from-above
NPC - https://www.wowhead.com/npc=41298
Quest Item - https://www.wowhead.com/item=56048

from WoWHead or our Armory

**What is happening:**
The Quest item should be used to summon a airstrike to destroy the buildings in the village, the item can be used but no airstrike happens and the buildings are already on fire in the area. I believe this also requires the prerequisite quest (ID 25839) #302 to be completed but is available without it 

**What should happen:**
Quest item should summon airstrike to destroy building in village, causing plane to fly over and buildings to burn which counts towards quest completion. 

![world of warcraft 08_03_2019 14_16_35](https://user-images.githubusercontent.com/45798884/54033951-9bc46d80-41ad-11e9-9a3d-ddef8b7f56de.png)

**Comment by bagi84** [comment]
Added # number for reported Chain quest

**Comment by iTz-AddriX** [comment]
**Confirmed** #4310

**Comment by mfranca0009** [comment]
Fires are being shown from this gameobject, this is the only reference I could find for the object:
https://db.rpwow.com/?object=182090

Displays the large flames on the camp buildings, will need to adjust it so they are spawned in when the planes are done firing rockets, via script.

**Comment by mfranca0009** [comment]
All set 👍

**Comment by Echinaceax** [comment]
confirmed fixed in ptr 

![image](https://user-images.githubusercontent.com/39439201/119491508-49f06980-bd5e-11eb-81e9-aa63ab177838.png)
![image](https://user-images.githubusercontent.com/39439201/119491760-976cd680-bd5e-11eb-88b2-56729815c217.png)
![image](https://user-images.githubusercontent.com/39439201/119492077-f4688c80-bd5e-11eb-841a-a9e321f19ac9.png)
![image](https://user-images.githubusercontent.com/39439201/119492268-24b02b00-bd5f-11eb-8304-b764a8ff8ae2.png)
