### ISSUE TITLE
Mage Waterelemental issue [spell=31687]

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#903]
**Links:**

from WoWHead or our Armory
[spell=31687]
https://www.wowhead.com/spell=31687/summon-water-elemental
**What is happening:**
There is an issue with  mage's waterelemental.
When the Mage sheep a mob then the elemental target it and shot at it.
should not engage that target.
This happens for atlest human Mages

**What should happen:**

This elemental should not target a polymorted target

**Comment by wow-mania** [comment]
pretty sure this is not valid.

**Comment by Saintres** [comment]
Better ?

**Comment by Keader** [comment]
Idk what blizzard did with polymorph...
But code is correct.
The problem here is: CC that break with damage, use AURA_INTERRUPT_FLAG_TAKE_DAMAGE in wotlk.
On cataclysm, Polymorph dont have that.
So... i realy think that blizzard removed damage break part...
@Dranah can take a search?

**Comment by Saintres** [comment]
But the water elemental should not engage a fight with a polymorted target.
If i as mage have 2 ot more mobs to fight i can polymort 1 and shoot on the others. 
But if my waterelemental start to fight the one i polymort then its all for nothing.
That cant be what Blizz was thinking.

**Comment by Keader** [comment]
Yes @Saintres it's wotlk behavior.
Not sure if cataclysm uses the same, because of AURA_INTERRUPT_FLAG_TAKE_DAMAGE missing...
That's why we need find some evidence of it.

**Comment by Saintres** [comment]
Then polymort is useless if u have the waterelemental up.

**Comment by Keader** [comment]
Is not, because it dont break on damage.

**Comment by Dranah** [comment]
I do recall a difference between lk and cata in this behavior. Mages complaining that the elemental's AI has gone stupid in cataclysm. I'm afraid this is a blizzlike issue.
The workaround is to set the elemental to passive and add a /cast waterbolt macro to one of your main rotation spells so that it starts attacking when you need.
Here's a discussion on MMO about it:
https://www.mmo-champion.com/threads/824565-Elemental-breaking-polymorph
And yes this has only been a problem once cata launched. Wotlk behavior was different.
