### ISSUE TITLE
[Spell] Bandit's Guile

### ISSUE THREAD

**Issue by Kitzunu** [WoWManiaUK/Blackwing-Lair#934]
https://wow.gamepedia.com/Bandit%27s_Guile
ID: 84652 , 84653 , 84654 ( rank 1 2 3)
Shallow Insight : 84745
Moderate Insight : 84746
Deep Insight : 84747

**How it works:**
Does not proc

**How it should work:**
After you have used Sinister Strike x4 you should get a new level of Insight, from none to Shallow to Moderate and finally Deep Insight.

![image](https://user-images.githubusercontent.com/24550914/54480216-061c8400-4826-11e9-82ca-67eaeba62100.png)

**Comment by Dranah** [comment]
This now procs as intended but the proc is cosmetic. You get the different color buffs but none of them give you any actual damage boost.
My test char does same damage
77-78 main hand
57-59 offhand
384-387 sinister strike 
with no buff, green, yellow and red alike.

**Comment by Keader** [comment]
lul was a typo.
I was casting spell in rogue instead target ._.

**Comment by Dranah** [comment]
The damage boost now works but there's another problem.
"Striking a different opponent will begin the cycle anew."
This does not work when you have Red buff (Deep Insight 84747).
It works fine with green and yellow active, hitting another enemy will reset the buff and start counting for new target. However if you are Red, it is unable to restart. You have to wait for the buff to expire in order to be able to start stacking it on another target. Right clicking to remove buff does not work.

What should happen: Changing target should instantly make you lose your current buff even if it's already highest (red) version. It should be possible to remove the effect with right click, as it's a beneficial buff.

**Comment by Keader** [comment]
Hmm, i dont know that.
Fixed.

**Comment by Dranah** [comment]
Well, the right clicking doesnt work, but we can live without that... the rest is fixed.
