### ISSUE TITLE
[quest=27467] [Buried Blades] - Eastern Plaguelands

### ISSUE THREAD

**Issue by Saintres** [WoWManiaUK/Blackwing-Lair#993]
**Links:**
[quest=27467]
https://www.wowhead.com/quest=27467/buried-blades
[item=61302]
from WoWHead or our Armory

**What is happening:**
Im suppose to use the sword [item=61302] to put in the corpses i kill
but it ends up with i have the sword in my own neck instead and i dont need any corpses.
I can get the quest done without to kill anyone.

**What should happen:**
The sword should be in the corpses instead of in my own back/neck

**Comment by Echinaceax** [comment]
Virtual bug only

**Comment by mfranca0009** [comment]
Needs testing in PTR

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR
stays in her hand now 👍 

![fixed stays in hand](https://user-images.githubusercontent.com/39439201/88581233-26309a00-d04d-11ea-8988-55264e426f87.jpg)


**did however find another issue** 
- can use quest item on the same mob over and over to get 10 credits 😄 

![repeatable on one mob](https://user-images.githubusercontent.com/39439201/88581695-d69e9e00-d04d-11ea-8b4e-1a668c08cafa.jpg)

**Comment by mfranca0009** [comment]
I did notice the blade stays in hand, but I'm assuming this is just how the spell was maybe? If you look at the slain scourged trooper the blade is buried with the corpse 👍

**Comment by Echinaceax** [comment]
edited above new issue @mfranca0009

**Comment by mfranca0009** [comment]
Will fix tonight and edit SQL file 👍

**Comment by mfranca0009** [comment]
Should be fixed now, just needs another test in PTR

**Comment by Echinaceax** [comment]
Confirmed fixed in PTR for 2nd issue too thanks @mfranca0009
